// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: device.proto

package devicesvr

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GetDevicesBySnListRequest 根据 SN 列表查询设备信息
type GetDevicesBySnListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SnList        []string               `protobuf:"bytes,1,rep,name=snList,proto3" json:"snList,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDevicesBySnListRequest) Reset() {
	*x = GetDevicesBySnListRequest{}
	mi := &file_device_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDevicesBySnListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDevicesBySnListRequest) ProtoMessage() {}

func (x *GetDevicesBySnListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_device_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDevicesBySnListRequest.ProtoReflect.Descriptor instead.
func (*GetDevicesBySnListRequest) Descriptor() ([]byte, []int) {
	return file_device_proto_rawDescGZIP(), []int{0}
}

func (x *GetDevicesBySnListRequest) GetSnList() []string {
	if x != nil {
		return x.SnList
	}
	return nil
}

// DeviceInfo 设备信息（不包含敏感字段 scramble_code）
type DeviceInfo struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Id                     string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SnNumber               string                 `protobuf:"bytes,2,opt,name=snNumber,proto3" json:"snNumber,omitempty"`                              // 设备序列号
	ImeiNumber             string                 `protobuf:"bytes,3,opt,name=imeiNumber,proto3" json:"imeiNumber,omitempty"`                          // 设备 IMEI 号
	Owner                  string                 `protobuf:"bytes,4,opt,name=owner,proto3" json:"owner,omitempty"`                                    // 创建者/所有者
	OrgId                  int64                  `protobuf:"varint,5,opt,name=orgId,proto3" json:"orgId,omitempty"`                                   // 机构 ID
	CreateTime             *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=createTime,proto3" json:"createTime,omitempty"`                          // 创建时间
	UpdateTime             *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updateTime,proto3" json:"updateTime,omitempty"`                          // 更新时间
	Name                   string                 `protobuf:"bytes,8,opt,name=name,proto3" json:"name,omitempty"`                                      // 设备名称
	Token                  string                 `protobuf:"bytes,9,opt,name=token,proto3" json:"token,omitempty"`                                    // 设备 token
	Alias                  string                 `protobuf:"bytes,10,opt,name=alias,proto3" json:"alias,omitempty"`                                   // 设备别名
	Pid                    string                 `protobuf:"bytes,11,opt,name=pid,proto3" json:"pid,omitempty"`                                       // 产品 ID
	Gid                    string                 `protobuf:"bytes,12,opt,name=gid,proto3" json:"gid,omitempty"`                                       // 分组 ID
	Description            string                 `protobuf:"bytes,13,opt,name=description,proto3" json:"description,omitempty"`                       // 产品说明
	Status                 string                 `protobuf:"bytes,14,opt,name=status,proto3" json:"status,omitempty"`                                 // 状态
	FactoryInstallVersion  string                 `protobuf:"bytes,15,opt,name=factoryInstallVersion,proto3" json:"factoryInstallVersion,omitempty"`   // 出厂安装版本
	FactoryDownloadVersion string                 `protobuf:"bytes,16,opt,name=factoryDownloadVersion,proto3" json:"factoryDownloadVersion,omitempty"` // 出厂下载版本
	OtaVersion             string                 `protobuf:"bytes,17,opt,name=otaVersion,proto3" json:"otaVersion,omitempty"`                         // 固件版本（已废弃，向后兼容）
	RosDomainId            int64                  `protobuf:"varint,18,opt,name=rosDomainId,proto3" json:"rosDomainId,omitempty"`                      // ROS 域 ID
	ParentId               string                 `protobuf:"bytes,19,opt,name=parentId,proto3" json:"parentId,omitempty"`                             // 父设备 ID（子设备时父设备为网关）
	DeviceType             string                 `protobuf:"bytes,20,opt,name=deviceType,proto3" json:"deviceType,omitempty"`                         // 设备类型
	LinkStatus             string                 `protobuf:"bytes,21,opt,name=linkStatus,proto3" json:"linkStatus,omitempty"`                         // 连接状态
	LastTime               *timestamppb.Timestamp `protobuf:"bytes,22,opt,name=lastTime,proto3" json:"lastTime,omitempty"`                             // 最后一次在线时间
	LifecycleStatus        string                 `protobuf:"bytes,23,opt,name=lifecycleStatus,proto3" json:"lifecycleStatus,omitempty"`               // 生命周期状态
	DeviceBelongingType    string                 `protobuf:"bytes,24,opt,name=deviceBelongingType,proto3" json:"deviceBelongingType,omitempty"`       // 设备归属类型
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *DeviceInfo) Reset() {
	*x = DeviceInfo{}
	mi := &file_device_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceInfo) ProtoMessage() {}

func (x *DeviceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_device_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceInfo.ProtoReflect.Descriptor instead.
func (*DeviceInfo) Descriptor() ([]byte, []int) {
	return file_device_proto_rawDescGZIP(), []int{1}
}

func (x *DeviceInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeviceInfo) GetSnNumber() string {
	if x != nil {
		return x.SnNumber
	}
	return ""
}

func (x *DeviceInfo) GetImeiNumber() string {
	if x != nil {
		return x.ImeiNumber
	}
	return ""
}

func (x *DeviceInfo) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *DeviceInfo) GetOrgId() int64 {
	if x != nil {
		return x.OrgId
	}
	return 0
}

func (x *DeviceInfo) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *DeviceInfo) GetUpdateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateTime
	}
	return nil
}

func (x *DeviceInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DeviceInfo) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *DeviceInfo) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

func (x *DeviceInfo) GetPid() string {
	if x != nil {
		return x.Pid
	}
	return ""
}

func (x *DeviceInfo) GetGid() string {
	if x != nil {
		return x.Gid
	}
	return ""
}

func (x *DeviceInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *DeviceInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *DeviceInfo) GetFactoryInstallVersion() string {
	if x != nil {
		return x.FactoryInstallVersion
	}
	return ""
}

func (x *DeviceInfo) GetFactoryDownloadVersion() string {
	if x != nil {
		return x.FactoryDownloadVersion
	}
	return ""
}

func (x *DeviceInfo) GetOtaVersion() string {
	if x != nil {
		return x.OtaVersion
	}
	return ""
}

func (x *DeviceInfo) GetRosDomainId() int64 {
	if x != nil {
		return x.RosDomainId
	}
	return 0
}

func (x *DeviceInfo) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

func (x *DeviceInfo) GetDeviceType() string {
	if x != nil {
		return x.DeviceType
	}
	return ""
}

func (x *DeviceInfo) GetLinkStatus() string {
	if x != nil {
		return x.LinkStatus
	}
	return ""
}

func (x *DeviceInfo) GetLastTime() *timestamppb.Timestamp {
	if x != nil {
		return x.LastTime
	}
	return nil
}

func (x *DeviceInfo) GetLifecycleStatus() string {
	if x != nil {
		return x.LifecycleStatus
	}
	return ""
}

func (x *DeviceInfo) GetDeviceBelongingType() string {
	if x != nil {
		return x.DeviceBelongingType
	}
	return ""
}

// GetDevicesBySnListResponse 设备信息列表
type GetDevicesInfoListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Devices       []*DeviceInfo          `protobuf:"bytes,1,rep,name=devices,proto3" json:"devices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDevicesInfoListResponse) Reset() {
	*x = GetDevicesInfoListResponse{}
	mi := &file_device_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDevicesInfoListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDevicesInfoListResponse) ProtoMessage() {}

func (x *GetDevicesInfoListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_device_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDevicesInfoListResponse.ProtoReflect.Descriptor instead.
func (*GetDevicesInfoListResponse) Descriptor() ([]byte, []int) {
	return file_device_proto_rawDescGZIP(), []int{2}
}

func (x *GetDevicesInfoListResponse) GetDevices() []*DeviceInfo {
	if x != nil {
		return x.Devices
	}
	return nil
}

// SearchDevicesRequest 根据 SN、名称、机器人类型查询设备信息（条件可选，支持组合查询）
type SearchDevicesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SnNumber      string                 `protobuf:"bytes,1,opt,name=snNumber,proto3" json:"snNumber,omitempty"`     // 设备序列号（精确匹配，空则忽略）
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`             // 设备名称（模糊匹配，空则忽略）
	DeviceType    string                 `protobuf:"bytes,3,opt,name=deviceType,proto3" json:"deviceType,omitempty"` // 机器人类型/设备类型（精确匹配，空则忽略）
	DeviceId      string                 `protobuf:"bytes,4,opt,name=deviceId,proto3" json:"deviceId,omitempty"`     //设备id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchDevicesRequest) Reset() {
	*x = SearchDevicesRequest{}
	mi := &file_device_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchDevicesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchDevicesRequest) ProtoMessage() {}

func (x *SearchDevicesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_device_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchDevicesRequest.ProtoReflect.Descriptor instead.
func (*SearchDevicesRequest) Descriptor() ([]byte, []int) {
	return file_device_proto_rawDescGZIP(), []int{3}
}

func (x *SearchDevicesRequest) GetSnNumber() string {
	if x != nil {
		return x.SnNumber
	}
	return ""
}

func (x *SearchDevicesRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SearchDevicesRequest) GetDeviceType() string {
	if x != nil {
		return x.DeviceType
	}
	return ""
}

func (x *SearchDevicesRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

// DeviceMetricDaily 设备每日累计指标
type DeviceMetricDaily struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CreateTime    *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=createTime,proto3" json:"createTime,omitempty"`
	UpdateTime    *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=updateTime,proto3" json:"updateTime,omitempty"`
	DeviceId      string                 `protobuf:"bytes,4,opt,name=deviceId,proto3" json:"deviceId,omitempty"`         // device id
	SnNumber      string                 `protobuf:"bytes,5,opt,name=snNumber,proto3" json:"snNumber,omitempty"`         // device sn number
	MetricType    string                 `protobuf:"bytes,6,opt,name=metricType,proto3" json:"metricType,omitempty"`     // metric type
	StatDate      *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=statDate,proto3" json:"statDate,omitempty"`         // stat date
	MetricValue   float64                `protobuf:"fixed64,8,opt,name=metricValue,proto3" json:"metricValue,omitempty"` // cumulative metric value
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceMetricDaily) Reset() {
	*x = DeviceMetricDaily{}
	mi := &file_device_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceMetricDaily) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceMetricDaily) ProtoMessage() {}

func (x *DeviceMetricDaily) ProtoReflect() protoreflect.Message {
	mi := &file_device_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceMetricDaily.ProtoReflect.Descriptor instead.
func (*DeviceMetricDaily) Descriptor() ([]byte, []int) {
	return file_device_proto_rawDescGZIP(), []int{4}
}

func (x *DeviceMetricDaily) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeviceMetricDaily) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *DeviceMetricDaily) GetUpdateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateTime
	}
	return nil
}

func (x *DeviceMetricDaily) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *DeviceMetricDaily) GetSnNumber() string {
	if x != nil {
		return x.SnNumber
	}
	return ""
}

func (x *DeviceMetricDaily) GetMetricType() string {
	if x != nil {
		return x.MetricType
	}
	return ""
}

func (x *DeviceMetricDaily) GetStatDate() *timestamppb.Timestamp {
	if x != nil {
		return x.StatDate
	}
	return nil
}

func (x *DeviceMetricDaily) GetMetricValue() float64 {
	if x != nil {
		return x.MetricValue
	}
	return 0
}

// GetDailyMetricsRequest 查询指定设备在日期范围内的每日指标
type GetDailyMetricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SnList        []string               `protobuf:"bytes,1,rep,name=snList,proto3" json:"snList,omitempty"`
	StartDate     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=startDate,proto3" json:"startDate,omitempty"`
	EndDate       *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=endDate,proto3" json:"endDate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDailyMetricsRequest) Reset() {
	*x = GetDailyMetricsRequest{}
	mi := &file_device_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDailyMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDailyMetricsRequest) ProtoMessage() {}

func (x *GetDailyMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_device_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDailyMetricsRequest.ProtoReflect.Descriptor instead.
func (*GetDailyMetricsRequest) Descriptor() ([]byte, []int) {
	return file_device_proto_rawDescGZIP(), []int{5}
}

func (x *GetDailyMetricsRequest) GetSnList() []string {
	if x != nil {
		return x.SnList
	}
	return nil
}

func (x *GetDailyMetricsRequest) GetStartDate() *timestamppb.Timestamp {
	if x != nil {
		return x.StartDate
	}
	return nil
}

func (x *GetDailyMetricsRequest) GetEndDate() *timestamppb.Timestamp {
	if x != nil {
		return x.EndDate
	}
	return nil
}

// GetLatestMetricsBeforeDateRequest 查询指定设备和指标在某日期前最近一条累计指标
type GetLatestMetricsBeforeDateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceSns     []string               `protobuf:"bytes,1,rep,name=deviceSns,proto3" json:"deviceSns,omitempty"`
	BeforeDate    *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=beforeDate,proto3" json:"beforeDate,omitempty"`
	MetricTypes   []string               `protobuf:"bytes,3,rep,name=metricTypes,proto3" json:"metricTypes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLatestMetricsBeforeDateRequest) Reset() {
	*x = GetLatestMetricsBeforeDateRequest{}
	mi := &file_device_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLatestMetricsBeforeDateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLatestMetricsBeforeDateRequest) ProtoMessage() {}

func (x *GetLatestMetricsBeforeDateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_device_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLatestMetricsBeforeDateRequest.ProtoReflect.Descriptor instead.
func (*GetLatestMetricsBeforeDateRequest) Descriptor() ([]byte, []int) {
	return file_device_proto_rawDescGZIP(), []int{6}
}

func (x *GetLatestMetricsBeforeDateRequest) GetDeviceSns() []string {
	if x != nil {
		return x.DeviceSns
	}
	return nil
}

func (x *GetLatestMetricsBeforeDateRequest) GetBeforeDate() *timestamppb.Timestamp {
	if x != nil {
		return x.BeforeDate
	}
	return nil
}

func (x *GetLatestMetricsBeforeDateRequest) GetMetricTypes() []string {
	if x != nil {
		return x.MetricTypes
	}
	return nil
}

// GetDailyMetricsByTypeRequest 查询指定设备在日期范围内的指定类型指标
type GetDailyMetricsByTypeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceSns     []string               `protobuf:"bytes,1,rep,name=deviceSns,proto3" json:"deviceSns,omitempty"`
	StartDate     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=startDate,proto3" json:"startDate,omitempty"`
	EndDate       *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=endDate,proto3" json:"endDate,omitempty"`
	MetricType    string                 `protobuf:"bytes,4,opt,name=metricType,proto3" json:"metricType,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDailyMetricsByTypeRequest) Reset() {
	*x = GetDailyMetricsByTypeRequest{}
	mi := &file_device_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDailyMetricsByTypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDailyMetricsByTypeRequest) ProtoMessage() {}

func (x *GetDailyMetricsByTypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_device_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDailyMetricsByTypeRequest.ProtoReflect.Descriptor instead.
func (*GetDailyMetricsByTypeRequest) Descriptor() ([]byte, []int) {
	return file_device_proto_rawDescGZIP(), []int{7}
}

func (x *GetDailyMetricsByTypeRequest) GetDeviceSns() []string {
	if x != nil {
		return x.DeviceSns
	}
	return nil
}

func (x *GetDailyMetricsByTypeRequest) GetStartDate() *timestamppb.Timestamp {
	if x != nil {
		return x.StartDate
	}
	return nil
}

func (x *GetDailyMetricsByTypeRequest) GetEndDate() *timestamppb.Timestamp {
	if x != nil {
		return x.EndDate
	}
	return nil
}

func (x *GetDailyMetricsByTypeRequest) GetMetricType() string {
	if x != nil {
		return x.MetricType
	}
	return ""
}

// GetDeviceMetricsListResponse 设备每日指标列表
type GetDeviceMetricsListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metrics       []*DeviceMetricDaily   `protobuf:"bytes,1,rep,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeviceMetricsListResponse) Reset() {
	*x = GetDeviceMetricsListResponse{}
	mi := &file_device_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeviceMetricsListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeviceMetricsListResponse) ProtoMessage() {}

func (x *GetDeviceMetricsListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_device_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeviceMetricsListResponse.ProtoReflect.Descriptor instead.
func (*GetDeviceMetricsListResponse) Descriptor() ([]byte, []int) {
	return file_device_proto_rawDescGZIP(), []int{8}
}

func (x *GetDeviceMetricsListResponse) GetMetrics() []*DeviceMetricDaily {
	if x != nil {
		return x.Metrics
	}
	return nil
}

// BatchSaveMetricsRequest 批量保存设备每日累计指标
type BatchSaveMetricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metrics       []*DeviceMetricDaily   `protobuf:"bytes,1,rep,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchSaveMetricsRequest) Reset() {
	*x = BatchSaveMetricsRequest{}
	mi := &file_device_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchSaveMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchSaveMetricsRequest) ProtoMessage() {}

func (x *BatchSaveMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_device_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchSaveMetricsRequest.ProtoReflect.Descriptor instead.
func (*BatchSaveMetricsRequest) Descriptor() ([]byte, []int) {
	return file_device_proto_rawDescGZIP(), []int{9}
}

func (x *BatchSaveMetricsRequest) GetMetrics() []*DeviceMetricDaily {
	if x != nil {
		return x.Metrics
	}
	return nil
}

// BatchSaveMetricsResponse 批量保存结果
type BatchSaveMetricsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchSaveMetricsResponse) Reset() {
	*x = BatchSaveMetricsResponse{}
	mi := &file_device_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchSaveMetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchSaveMetricsResponse) ProtoMessage() {}

func (x *BatchSaveMetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_device_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchSaveMetricsResponse.ProtoReflect.Descriptor instead.
func (*BatchSaveMetricsResponse) Descriptor() ([]byte, []int) {
	return file_device_proto_rawDescGZIP(), []int{10}
}

var File_device_proto protoreflect.FileDescriptor

const file_device_proto_rawDesc = "" +
	"\n" +
	"\fdevice.proto\x12\tdevicesvr\x1a\x1fgoogle/protobuf/timestamp.proto\"3\n" +
	"\x19GetDevicesBySnListRequest\x12\x16\n" +
	"\x06snList\x18\x01 \x03(\tR\x06snList\"\xba\x06\n" +
	"\n" +
	"DeviceInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bsnNumber\x18\x02 \x01(\tR\bsnNumber\x12\x1e\n" +
	"\n" +
	"imeiNumber\x18\x03 \x01(\tR\n" +
	"imeiNumber\x12\x14\n" +
	"\x05owner\x18\x04 \x01(\tR\x05owner\x12\x14\n" +
	"\x05orgId\x18\x05 \x01(\x03R\x05orgId\x12:\n" +
	"\n" +
	"createTime\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"createTime\x12:\n" +
	"\n" +
	"updateTime\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"updateTime\x12\x12\n" +
	"\x04name\x18\b \x01(\tR\x04name\x12\x14\n" +
	"\x05token\x18\t \x01(\tR\x05token\x12\x14\n" +
	"\x05alias\x18\n" +
	" \x01(\tR\x05alias\x12\x10\n" +
	"\x03pid\x18\v \x01(\tR\x03pid\x12\x10\n" +
	"\x03gid\x18\f \x01(\tR\x03gid\x12 \n" +
	"\vdescription\x18\r \x01(\tR\vdescription\x12\x16\n" +
	"\x06status\x18\x0e \x01(\tR\x06status\x124\n" +
	"\x15factoryInstallVersion\x18\x0f \x01(\tR\x15factoryInstallVersion\x126\n" +
	"\x16factoryDownloadVersion\x18\x10 \x01(\tR\x16factoryDownloadVersion\x12\x1e\n" +
	"\n" +
	"otaVersion\x18\x11 \x01(\tR\n" +
	"otaVersion\x12 \n" +
	"\vrosDomainId\x18\x12 \x01(\x03R\vrosDomainId\x12\x1a\n" +
	"\bparentId\x18\x13 \x01(\tR\bparentId\x12\x1e\n" +
	"\n" +
	"deviceType\x18\x14 \x01(\tR\n" +
	"deviceType\x12\x1e\n" +
	"\n" +
	"linkStatus\x18\x15 \x01(\tR\n" +
	"linkStatus\x126\n" +
	"\blastTime\x18\x16 \x01(\v2\x1a.google.protobuf.TimestampR\blastTime\x12(\n" +
	"\x0flifecycleStatus\x18\x17 \x01(\tR\x0flifecycleStatus\x120\n" +
	"\x13deviceBelongingType\x18\x18 \x01(\tR\x13deviceBelongingType\"M\n" +
	"\x1aGetDevicesInfoListResponse\x12/\n" +
	"\adevices\x18\x01 \x03(\v2\x15.devicesvr.DeviceInfoR\adevices\"\x82\x01\n" +
	"\x14SearchDevicesRequest\x12\x1a\n" +
	"\bsnNumber\x18\x01 \x01(\tR\bsnNumber\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1e\n" +
	"\n" +
	"deviceType\x18\x03 \x01(\tR\n" +
	"deviceType\x12\x1a\n" +
	"\bdeviceId\x18\x04 \x01(\tR\bdeviceId\"\xcd\x02\n" +
	"\x11DeviceMetricDaily\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12:\n" +
	"\n" +
	"createTime\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"createTime\x12:\n" +
	"\n" +
	"updateTime\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"updateTime\x12\x1a\n" +
	"\bdeviceId\x18\x04 \x01(\tR\bdeviceId\x12\x1a\n" +
	"\bsnNumber\x18\x05 \x01(\tR\bsnNumber\x12\x1e\n" +
	"\n" +
	"metricType\x18\x06 \x01(\tR\n" +
	"metricType\x126\n" +
	"\bstatDate\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\bstatDate\x12 \n" +
	"\vmetricValue\x18\b \x01(\x01R\vmetricValue\"\xa0\x01\n" +
	"\x16GetDailyMetricsRequest\x12\x16\n" +
	"\x06snList\x18\x01 \x03(\tR\x06snList\x128\n" +
	"\tstartDate\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tstartDate\x124\n" +
	"\aendDate\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\aendDate\"\x9f\x01\n" +
	"!GetLatestMetricsBeforeDateRequest\x12\x1c\n" +
	"\tdeviceSns\x18\x01 \x03(\tR\tdeviceSns\x12:\n" +
	"\n" +
	"beforeDate\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"beforeDate\x12 \n" +
	"\vmetricTypes\x18\x03 \x03(\tR\vmetricTypes\"\xcc\x01\n" +
	"\x1cGetDailyMetricsByTypeRequest\x12\x1c\n" +
	"\tdeviceSns\x18\x01 \x03(\tR\tdeviceSns\x128\n" +
	"\tstartDate\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tstartDate\x124\n" +
	"\aendDate\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\aendDate\x12\x1e\n" +
	"\n" +
	"metricType\x18\x04 \x01(\tR\n" +
	"metricType\"V\n" +
	"\x1cGetDeviceMetricsListResponse\x126\n" +
	"\ametrics\x18\x01 \x03(\v2\x1c.devicesvr.DeviceMetricDailyR\ametrics\"Q\n" +
	"\x17BatchSaveMetricsRequest\x126\n" +
	"\ametrics\x18\x01 \x03(\v2\x1c.devicesvr.DeviceMetricDailyR\ametrics\"\x1a\n" +
	"\x18BatchSaveMetricsResponse2\xf2\x04\n" +
	"\rDeviceService\x12a\n" +
	"\x12GetDevicesBySnList\x12$.devicesvr.GetDevicesBySnListRequest\x1a%.devicesvr.GetDevicesInfoListResponse\x12b\n" +
	"\x18SearchDevicesByCondition\x12\x1f.devicesvr.SearchDevicesRequest\x1a%.devicesvr.GetDevicesInfoListResponse\x12]\n" +
	"\x0fGetDailyMetrics\x12!.devicesvr.GetDailyMetricsRequest\x1a'.devicesvr.GetDeviceMetricsListResponse\x12s\n" +
	"\x1aGetLatestMetricsBeforeDate\x12,.devicesvr.GetLatestMetricsBeforeDateRequest\x1a'.devicesvr.GetDeviceMetricsListResponse\x12i\n" +
	"\x15GetDailyMetricsByType\x12'.devicesvr.GetDailyMetricsByTypeRequest\x1a'.devicesvr.GetDeviceMetricsListResponse\x12[\n" +
	"\x10BatchSaveMetrics\x12\".devicesvr.BatchSaveMetricsRequest\x1a#.devicesvr.BatchSaveMetricsResponseB\x1aZ\x18service/device;devicesvrb\x06proto3"

var (
	file_device_proto_rawDescOnce sync.Once
	file_device_proto_rawDescData []byte
)

func file_device_proto_rawDescGZIP() []byte {
	file_device_proto_rawDescOnce.Do(func() {
		file_device_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_device_proto_rawDesc), len(file_device_proto_rawDesc)))
	})
	return file_device_proto_rawDescData
}

var file_device_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_device_proto_goTypes = []any{
	(*GetDevicesBySnListRequest)(nil),         // 0: devicesvr.GetDevicesBySnListRequest
	(*DeviceInfo)(nil),                        // 1: devicesvr.DeviceInfo
	(*GetDevicesInfoListResponse)(nil),        // 2: devicesvr.GetDevicesInfoListResponse
	(*SearchDevicesRequest)(nil),              // 3: devicesvr.SearchDevicesRequest
	(*DeviceMetricDaily)(nil),                 // 4: devicesvr.DeviceMetricDaily
	(*GetDailyMetricsRequest)(nil),            // 5: devicesvr.GetDailyMetricsRequest
	(*GetLatestMetricsBeforeDateRequest)(nil), // 6: devicesvr.GetLatestMetricsBeforeDateRequest
	(*GetDailyMetricsByTypeRequest)(nil),      // 7: devicesvr.GetDailyMetricsByTypeRequest
	(*GetDeviceMetricsListResponse)(nil),      // 8: devicesvr.GetDeviceMetricsListResponse
	(*BatchSaveMetricsRequest)(nil),           // 9: devicesvr.BatchSaveMetricsRequest
	(*BatchSaveMetricsResponse)(nil),          // 10: devicesvr.BatchSaveMetricsResponse
	(*timestamppb.Timestamp)(nil),             // 11: google.protobuf.Timestamp
}
var file_device_proto_depIdxs = []int32{
	11, // 0: devicesvr.DeviceInfo.createTime:type_name -> google.protobuf.Timestamp
	11, // 1: devicesvr.DeviceInfo.updateTime:type_name -> google.protobuf.Timestamp
	11, // 2: devicesvr.DeviceInfo.lastTime:type_name -> google.protobuf.Timestamp
	1,  // 3: devicesvr.GetDevicesInfoListResponse.devices:type_name -> devicesvr.DeviceInfo
	11, // 4: devicesvr.DeviceMetricDaily.createTime:type_name -> google.protobuf.Timestamp
	11, // 5: devicesvr.DeviceMetricDaily.updateTime:type_name -> google.protobuf.Timestamp
	11, // 6: devicesvr.DeviceMetricDaily.statDate:type_name -> google.protobuf.Timestamp
	11, // 7: devicesvr.GetDailyMetricsRequest.startDate:type_name -> google.protobuf.Timestamp
	11, // 8: devicesvr.GetDailyMetricsRequest.endDate:type_name -> google.protobuf.Timestamp
	11, // 9: devicesvr.GetLatestMetricsBeforeDateRequest.beforeDate:type_name -> google.protobuf.Timestamp
	11, // 10: devicesvr.GetDailyMetricsByTypeRequest.startDate:type_name -> google.protobuf.Timestamp
	11, // 11: devicesvr.GetDailyMetricsByTypeRequest.endDate:type_name -> google.protobuf.Timestamp
	4,  // 12: devicesvr.GetDeviceMetricsListResponse.metrics:type_name -> devicesvr.DeviceMetricDaily
	4,  // 13: devicesvr.BatchSaveMetricsRequest.metrics:type_name -> devicesvr.DeviceMetricDaily
	0,  // 14: devicesvr.DeviceService.GetDevicesBySnList:input_type -> devicesvr.GetDevicesBySnListRequest
	3,  // 15: devicesvr.DeviceService.SearchDevicesByCondition:input_type -> devicesvr.SearchDevicesRequest
	5,  // 16: devicesvr.DeviceService.GetDailyMetrics:input_type -> devicesvr.GetDailyMetricsRequest
	6,  // 17: devicesvr.DeviceService.GetLatestMetricsBeforeDate:input_type -> devicesvr.GetLatestMetricsBeforeDateRequest
	7,  // 18: devicesvr.DeviceService.GetDailyMetricsByType:input_type -> devicesvr.GetDailyMetricsByTypeRequest
	9,  // 19: devicesvr.DeviceService.BatchSaveMetrics:input_type -> devicesvr.BatchSaveMetricsRequest
	2,  // 20: devicesvr.DeviceService.GetDevicesBySnList:output_type -> devicesvr.GetDevicesInfoListResponse
	2,  // 21: devicesvr.DeviceService.SearchDevicesByCondition:output_type -> devicesvr.GetDevicesInfoListResponse
	8,  // 22: devicesvr.DeviceService.GetDailyMetrics:output_type -> devicesvr.GetDeviceMetricsListResponse
	8,  // 23: devicesvr.DeviceService.GetLatestMetricsBeforeDate:output_type -> devicesvr.GetDeviceMetricsListResponse
	8,  // 24: devicesvr.DeviceService.GetDailyMetricsByType:output_type -> devicesvr.GetDeviceMetricsListResponse
	10, // 25: devicesvr.DeviceService.BatchSaveMetrics:output_type -> devicesvr.BatchSaveMetricsResponse
	20, // [20:26] is the sub-list for method output_type
	14, // [14:20] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_device_proto_init() }
func file_device_proto_init() {
	if File_device_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_device_proto_rawDesc), len(file_device_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_device_proto_goTypes,
		DependencyIndexes: file_device_proto_depIdxs,
		MessageInfos:      file_device_proto_msgTypes,
	}.Build()
	File_device_proto = out.File
	file_device_proto_goTypes = nil
	file_device_proto_depIdxs = nil
}
