// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: data_migrate.proto

package datamigrate

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MigrateTableDataRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 目标表名，如 "app_user"、"device_services" 等
	TableName string `protobuf:"bytes,1,opt,name=table_name,json=tableName,proto3" json:"table_name,omitempty"`
	// 操作类型："insert" 或 "update"
	OperateType string `protobuf:"bytes,2,opt,name=operate_type,json=operateType,proto3" json:"operate_type,omitempty"`
	// 字段和对应的值
	Data          map[string]string `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MigrateTableDataRequest) Reset() {
	*x = MigrateTableDataRequest{}
	mi := &file_data_migrate_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MigrateTableDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MigrateTableDataRequest) ProtoMessage() {}

func (x *MigrateTableDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_data_migrate_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MigrateTableDataRequest.ProtoReflect.Descriptor instead.
func (*MigrateTableDataRequest) Descriptor() ([]byte, []int) {
	return file_data_migrate_proto_rawDescGZIP(), []int{0}
}

func (x *MigrateTableDataRequest) GetTableName() string {
	if x != nil {
		return x.TableName
	}
	return ""
}

func (x *MigrateTableDataRequest) GetOperateType() string {
	if x != nil {
		return x.OperateType
	}
	return ""
}

func (x *MigrateTableDataRequest) GetData() map[string]string {
	if x != nil {
		return x.Data
	}
	return nil
}

type MigrateTableDataResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 状态码：0 成功，其他失败
	Status int32 `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	// 结果说明
	Message       string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MigrateTableDataResponse) Reset() {
	*x = MigrateTableDataResponse{}
	mi := &file_data_migrate_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MigrateTableDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MigrateTableDataResponse) ProtoMessage() {}

func (x *MigrateTableDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_data_migrate_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MigrateTableDataResponse.ProtoReflect.Descriptor instead.
func (*MigrateTableDataResponse) Descriptor() ([]byte, []int) {
	return file_data_migrate_proto_rawDescGZIP(), []int{1}
}

func (x *MigrateTableDataResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *MigrateTableDataResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type BatchMigrateTableDataRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 目标表名
	TableName string `protobuf:"bytes,1,opt,name=table_name,json=tableName,proto3" json:"table_name,omitempty"`
	// 操作类型："insert" 或 "update"
	OperateType string `protobuf:"bytes,2,opt,name=operate_type,json=operateType,proto3" json:"operate_type,omitempty"`
	// 批量数据，每条记录是一个 map<string, string>
	BatchData     []*BatchData `protobuf:"bytes,3,rep,name=batch_data,json=batchData,proto3" json:"batch_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchMigrateTableDataRequest) Reset() {
	*x = BatchMigrateTableDataRequest{}
	mi := &file_data_migrate_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchMigrateTableDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchMigrateTableDataRequest) ProtoMessage() {}

func (x *BatchMigrateTableDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_data_migrate_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchMigrateTableDataRequest.ProtoReflect.Descriptor instead.
func (*BatchMigrateTableDataRequest) Descriptor() ([]byte, []int) {
	return file_data_migrate_proto_rawDescGZIP(), []int{2}
}

func (x *BatchMigrateTableDataRequest) GetTableName() string {
	if x != nil {
		return x.TableName
	}
	return ""
}

func (x *BatchMigrateTableDataRequest) GetOperateType() string {
	if x != nil {
		return x.OperateType
	}
	return ""
}

func (x *BatchMigrateTableDataRequest) GetBatchData() []*BatchData {
	if x != nil {
		return x.BatchData
	}
	return nil
}

type BatchData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 字段和对应的值
	Data          map[string]string `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchData) Reset() {
	*x = BatchData{}
	mi := &file_data_migrate_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchData) ProtoMessage() {}

func (x *BatchData) ProtoReflect() protoreflect.Message {
	mi := &file_data_migrate_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchData.ProtoReflect.Descriptor instead.
func (*BatchData) Descriptor() ([]byte, []int) {
	return file_data_migrate_proto_rawDescGZIP(), []int{3}
}

func (x *BatchData) GetData() map[string]string {
	if x != nil {
		return x.Data
	}
	return nil
}

type BatchMigrateTableDataResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 状态码：0 全部成功，1 部分失败，2 全部失败
	Status int32 `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	// 成功条数
	SuccessCount int32 `protobuf:"varint,2,opt,name=success_count,json=successCount,proto3" json:"success_count,omitempty"`
	// 失败条数
	FailedCount int32 `protobuf:"varint,3,opt,name=failed_count,json=failedCount,proto3" json:"failed_count,omitempty"`
	// 结果说明
	Message string `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	// 失败详情
	FailedRecords []*FailedRecord `protobuf:"bytes,5,rep,name=failed_records,json=failedRecords,proto3" json:"failed_records,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchMigrateTableDataResponse) Reset() {
	*x = BatchMigrateTableDataResponse{}
	mi := &file_data_migrate_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchMigrateTableDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchMigrateTableDataResponse) ProtoMessage() {}

func (x *BatchMigrateTableDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_data_migrate_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchMigrateTableDataResponse.ProtoReflect.Descriptor instead.
func (*BatchMigrateTableDataResponse) Descriptor() ([]byte, []int) {
	return file_data_migrate_proto_rawDescGZIP(), []int{4}
}

func (x *BatchMigrateTableDataResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *BatchMigrateTableDataResponse) GetSuccessCount() int32 {
	if x != nil {
		return x.SuccessCount
	}
	return 0
}

func (x *BatchMigrateTableDataResponse) GetFailedCount() int32 {
	if x != nil {
		return x.FailedCount
	}
	return 0
}

func (x *BatchMigrateTableDataResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *BatchMigrateTableDataResponse) GetFailedRecords() []*FailedRecord {
	if x != nil {
		return x.FailedRecords
	}
	return nil
}

type FailedRecord struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 失败行索引
	RowIndex int32 `protobuf:"varint,1,opt,name=row_index,json=rowIndex,proto3" json:"row_index,omitempty"`
	// 失败原因
	Reason        string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FailedRecord) Reset() {
	*x = FailedRecord{}
	mi := &file_data_migrate_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FailedRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FailedRecord) ProtoMessage() {}

func (x *FailedRecord) ProtoReflect() protoreflect.Message {
	mi := &file_data_migrate_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FailedRecord.ProtoReflect.Descriptor instead.
func (*FailedRecord) Descriptor() ([]byte, []int) {
	return file_data_migrate_proto_rawDescGZIP(), []int{5}
}

func (x *FailedRecord) GetRowIndex() int32 {
	if x != nil {
		return x.RowIndex
	}
	return 0
}

func (x *FailedRecord) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_data_migrate_proto protoreflect.FileDescriptor

const file_data_migrate_proto_rawDesc = "" +
	"\n" +
	"\x12data_migrate.proto\x12\vdatamigrate\"\xd8\x01\n" +
	"\x17MigrateTableDataRequest\x12\x1d\n" +
	"\n" +
	"table_name\x18\x01 \x01(\tR\ttableName\x12!\n" +
	"\foperate_type\x18\x02 \x01(\tR\voperateType\x12B\n" +
	"\x04data\x18\x03 \x03(\v2..datamigrate.MigrateTableDataRequest.DataEntryR\x04data\x1a7\n" +
	"\tDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"L\n" +
	"\x18MigrateTableDataResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x05R\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x97\x01\n" +
	"\x1cBatchMigrateTableDataRequest\x12\x1d\n" +
	"\n" +
	"table_name\x18\x01 \x01(\tR\ttableName\x12!\n" +
	"\foperate_type\x18\x02 \x01(\tR\voperateType\x125\n" +
	"\n" +
	"batch_data\x18\x03 \x03(\v2\x16.datamigrate.BatchDataR\tbatchData\"z\n" +
	"\tBatchData\x124\n" +
	"\x04data\x18\x01 \x03(\v2 .datamigrate.BatchData.DataEntryR\x04data\x1a7\n" +
	"\tDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xdb\x01\n" +
	"\x1dBatchMigrateTableDataResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x05R\x06status\x12#\n" +
	"\rsuccess_count\x18\x02 \x01(\x05R\fsuccessCount\x12!\n" +
	"\ffailed_count\x18\x03 \x01(\x05R\vfailedCount\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12@\n" +
	"\x0efailed_records\x18\x05 \x03(\v2\x19.datamigrate.FailedRecordR\rfailedRecords\"C\n" +
	"\fFailedRecord\x12\x1b\n" +
	"\trow_index\x18\x01 \x01(\x05R\browIndex\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason2\xe5\x01\n" +
	"\x12DataMigrateService\x12_\n" +
	"\x10MigrateTableData\x12$.datamigrate.MigrateTableDataRequest\x1a%.datamigrate.MigrateTableDataResponse\x12n\n" +
	"\x15BatchMigrateTableData\x12).datamigrate.BatchMigrateTableDataRequest\x1a*.datamigrate.BatchMigrateTableDataResponseB\x1dZ\x1bservice/migrate;datamigrateb\x06proto3"

var (
	file_data_migrate_proto_rawDescOnce sync.Once
	file_data_migrate_proto_rawDescData []byte
)

func file_data_migrate_proto_rawDescGZIP() []byte {
	file_data_migrate_proto_rawDescOnce.Do(func() {
		file_data_migrate_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_data_migrate_proto_rawDesc), len(file_data_migrate_proto_rawDesc)))
	})
	return file_data_migrate_proto_rawDescData
}

var file_data_migrate_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_data_migrate_proto_goTypes = []any{
	(*MigrateTableDataRequest)(nil),       // 0: datamigrate.MigrateTableDataRequest
	(*MigrateTableDataResponse)(nil),      // 1: datamigrate.MigrateTableDataResponse
	(*BatchMigrateTableDataRequest)(nil),  // 2: datamigrate.BatchMigrateTableDataRequest
	(*BatchData)(nil),                     // 3: datamigrate.BatchData
	(*BatchMigrateTableDataResponse)(nil), // 4: datamigrate.BatchMigrateTableDataResponse
	(*FailedRecord)(nil),                  // 5: datamigrate.FailedRecord
	nil,                                   // 6: datamigrate.MigrateTableDataRequest.DataEntry
	nil,                                   // 7: datamigrate.BatchData.DataEntry
}
var file_data_migrate_proto_depIdxs = []int32{
	6, // 0: datamigrate.MigrateTableDataRequest.data:type_name -> datamigrate.MigrateTableDataRequest.DataEntry
	3, // 1: datamigrate.BatchMigrateTableDataRequest.batch_data:type_name -> datamigrate.BatchData
	7, // 2: datamigrate.BatchData.data:type_name -> datamigrate.BatchData.DataEntry
	5, // 3: datamigrate.BatchMigrateTableDataResponse.failed_records:type_name -> datamigrate.FailedRecord
	0, // 4: datamigrate.DataMigrateService.MigrateTableData:input_type -> datamigrate.MigrateTableDataRequest
	2, // 5: datamigrate.DataMigrateService.BatchMigrateTableData:input_type -> datamigrate.BatchMigrateTableDataRequest
	1, // 6: datamigrate.DataMigrateService.MigrateTableData:output_type -> datamigrate.MigrateTableDataResponse
	4, // 7: datamigrate.DataMigrateService.BatchMigrateTableData:output_type -> datamigrate.BatchMigrateTableDataResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_data_migrate_proto_init() }
func file_data_migrate_proto_init() {
	if File_data_migrate_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_data_migrate_proto_rawDesc), len(file_data_migrate_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_data_migrate_proto_goTypes,
		DependencyIndexes: file_data_migrate_proto_depIdxs,
		MessageInfos:      file_data_migrate_proto_msgTypes,
	}.Build()
	File_data_migrate_proto = out.File
	file_data_migrate_proto_goTypes = nil
	file_data_migrate_proto_depIdxs = nil
}
