// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.29.3
// source: data_migrate.proto

package datamigrate

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DataMigrateService_MigrateTableData_FullMethodName      = "/datamigrate.DataMigrateService/MigrateTableData"
	DataMigrateService_BatchMigrateTableData_FullMethodName = "/datamigrate.DataMigrateService/BatchMigrateTableData"
)

// DataMigrateServiceClient is the client API for DataMigrateService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DataMigrateServiceClient interface {
	MigrateTableData(ctx context.Context, in *MigrateTableDataRequest, opts ...grpc.CallOption) (*MigrateTableDataResponse, error)
	BatchMigrateTableData(ctx context.Context, in *BatchMigrateTableDataRequest, opts ...grpc.CallOption) (*BatchMigrateTableDataResponse, error)
}

type dataMigrateServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDataMigrateServiceClient(cc grpc.ClientConnInterface) DataMigrateServiceClient {
	return &dataMigrateServiceClient{cc}
}

func (c *dataMigrateServiceClient) MigrateTableData(ctx context.Context, in *MigrateTableDataRequest, opts ...grpc.CallOption) (*MigrateTableDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MigrateTableDataResponse)
	err := c.cc.Invoke(ctx, DataMigrateService_MigrateTableData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataMigrateServiceClient) BatchMigrateTableData(ctx context.Context, in *BatchMigrateTableDataRequest, opts ...grpc.CallOption) (*BatchMigrateTableDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchMigrateTableDataResponse)
	err := c.cc.Invoke(ctx, DataMigrateService_BatchMigrateTableData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DataMigrateServiceServer is the server API for DataMigrateService service.
// All implementations must embed UnimplementedDataMigrateServiceServer
// for forward compatibility.
type DataMigrateServiceServer interface {
	MigrateTableData(context.Context, *MigrateTableDataRequest) (*MigrateTableDataResponse, error)
	BatchMigrateTableData(context.Context, *BatchMigrateTableDataRequest) (*BatchMigrateTableDataResponse, error)
	mustEmbedUnimplementedDataMigrateServiceServer()
}

// UnimplementedDataMigrateServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDataMigrateServiceServer struct{}

func (UnimplementedDataMigrateServiceServer) MigrateTableData(context.Context, *MigrateTableDataRequest) (*MigrateTableDataResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MigrateTableData not implemented")
}
func (UnimplementedDataMigrateServiceServer) BatchMigrateTableData(context.Context, *BatchMigrateTableDataRequest) (*BatchMigrateTableDataResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BatchMigrateTableData not implemented")
}
func (UnimplementedDataMigrateServiceServer) mustEmbedUnimplementedDataMigrateServiceServer() {}
func (UnimplementedDataMigrateServiceServer) testEmbeddedByValue()                            {}

// UnsafeDataMigrateServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DataMigrateServiceServer will
// result in compilation errors.
type UnsafeDataMigrateServiceServer interface {
	mustEmbedUnimplementedDataMigrateServiceServer()
}

func RegisterDataMigrateServiceServer(s grpc.ServiceRegistrar, srv DataMigrateServiceServer) {
	// If the following call panics, it indicates UnimplementedDataMigrateServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DataMigrateService_ServiceDesc, srv)
}

func _DataMigrateService_MigrateTableData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MigrateTableDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataMigrateServiceServer).MigrateTableData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataMigrateService_MigrateTableData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataMigrateServiceServer).MigrateTableData(ctx, req.(*MigrateTableDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataMigrateService_BatchMigrateTableData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchMigrateTableDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataMigrateServiceServer).BatchMigrateTableData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataMigrateService_BatchMigrateTableData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataMigrateServiceServer).BatchMigrateTableData(ctx, req.(*BatchMigrateTableDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DataMigrateService_ServiceDesc is the grpc.ServiceDesc for DataMigrateService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DataMigrateService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "datamigrate.DataMigrateService",
	HandlerType: (*DataMigrateServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "MigrateTableData",
			Handler:    _DataMigrateService_MigrateTableData_Handler,
		},
		{
			MethodName: "BatchMigrateTableData",
			Handler:    _DataMigrateService_BatchMigrateTableData_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "data_migrate.proto",
}
