// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: app_user_game.proto

package usergame

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetUserGameExpRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 用户 ID。
	UserId string `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	// 用户手机号。
	Phone string `protobuf:"bytes,2,opt,name=phone,proto3" json:"phone,omitempty"`
	// 设备 SN。
	Sn            string `protobuf:"bytes,3,opt,name=sn,proto3" json:"sn,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserGameExpRequest) Reset() {
	*x = GetUserGameExpRequest{}
	mi := &file_app_user_game_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserGameExpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserGameExpRequest) ProtoMessage() {}

func (x *GetUserGameExpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_user_game_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserGameExpRequest.ProtoReflect.Descriptor instead.
func (*GetUserGameExpRequest) Descriptor() ([]byte, []int) {
	return file_app_user_game_proto_rawDescGZIP(), []int{0}
}

func (x *GetUserGameExpRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetUserGameExpRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *GetUserGameExpRequest) GetSn() string {
	if x != nil {
		return x.Sn
	}
	return ""
}

type GetUserGameExpResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 状态码：0 成功，其他失败。
	Status int32 `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	// 结果说明。
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// 用户游戏化等级信息。
	Data          *UserGameExpInfo `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserGameExpResponse) Reset() {
	*x = GetUserGameExpResponse{}
	mi := &file_app_user_game_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserGameExpResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserGameExpResponse) ProtoMessage() {}

func (x *GetUserGameExpResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_user_game_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserGameExpResponse.ProtoReflect.Descriptor instead.
func (*GetUserGameExpResponse) Descriptor() ([]byte, []int) {
	return file_app_user_game_proto_rawDescGZIP(), []int{1}
}

func (x *GetUserGameExpResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *GetUserGameExpResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetUserGameExpResponse) GetData() *UserGameExpInfo {
	if x != nil {
		return x.Data
	}
	return nil
}

type UserGameExpInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 等级名称，如 Lv1。
	LevelName string `protobuf:"bytes,1,opt,name=levelName,proto3" json:"levelName,omitempty"`
	// 等级 ID。
	LevelId int32 `protobuf:"varint,2,opt,name=levelId,proto3" json:"levelId,omitempty"`
	// 累计到当前的用户总经验值。
	CurExp int32 `protobuf:"varint,3,opt,name=curExp,proto3" json:"curExp,omitempty"`
	// 到下一个等级还需要的经验值。
	ExpLeftToNext int32 `protobuf:"varint,4,opt,name=expLeftToNext,proto3" json:"expLeftToNext,omitempty"`
	// 当前等级总经验值。
	CurLevelTotalExp int32 `protobuf:"varint,5,opt,name=curLevelTotalExp,proto3" json:"curLevelTotalExp,omitempty"`
	// 当下一级有未开放权益时的提示文案。
	NextPrivilegeText []string `protobuf:"bytes,6,rep,name=nextPrivilegeText,proto3" json:"nextPrivilegeText,omitempty"`
	// 页面展示的提示信息（经验与里程换算说明）。
	TipInfo *ContentInfo `protobuf:"bytes,7,opt,name=tipInfo,proto3" json:"tipInfo,omitempty"`
	// 当前等级权益列表。
	Privileges []*UserGameExpPrivilege `protobuf:"bytes,8,rep,name=privileges,proto3" json:"privileges,omitempty"`
	// 页面动效中展示的文案。
	LevelPageText *ContentInfo `protobuf:"bytes,9,opt,name=levelPageText,proto3" json:"levelPageText,omitempty"`
	// 是否需要展示页面动效。
	ShowPageAnimation bool `protobuf:"varint,10,opt,name=showPageAnimation,proto3" json:"showPageAnimation,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *UserGameExpInfo) Reset() {
	*x = UserGameExpInfo{}
	mi := &file_app_user_game_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserGameExpInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserGameExpInfo) ProtoMessage() {}

func (x *UserGameExpInfo) ProtoReflect() protoreflect.Message {
	mi := &file_app_user_game_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserGameExpInfo.ProtoReflect.Descriptor instead.
func (*UserGameExpInfo) Descriptor() ([]byte, []int) {
	return file_app_user_game_proto_rawDescGZIP(), []int{2}
}

func (x *UserGameExpInfo) GetLevelName() string {
	if x != nil {
		return x.LevelName
	}
	return ""
}

func (x *UserGameExpInfo) GetLevelId() int32 {
	if x != nil {
		return x.LevelId
	}
	return 0
}

func (x *UserGameExpInfo) GetCurExp() int32 {
	if x != nil {
		return x.CurExp
	}
	return 0
}

func (x *UserGameExpInfo) GetExpLeftToNext() int32 {
	if x != nil {
		return x.ExpLeftToNext
	}
	return 0
}

func (x *UserGameExpInfo) GetCurLevelTotalExp() int32 {
	if x != nil {
		return x.CurLevelTotalExp
	}
	return 0
}

func (x *UserGameExpInfo) GetNextPrivilegeText() []string {
	if x != nil {
		return x.NextPrivilegeText
	}
	return nil
}

func (x *UserGameExpInfo) GetTipInfo() *ContentInfo {
	if x != nil {
		return x.TipInfo
	}
	return nil
}

func (x *UserGameExpInfo) GetPrivileges() []*UserGameExpPrivilege {
	if x != nil {
		return x.Privileges
	}
	return nil
}

func (x *UserGameExpInfo) GetLevelPageText() *ContentInfo {
	if x != nil {
		return x.LevelPageText
	}
	return nil
}

func (x *UserGameExpInfo) GetShowPageAnimation() bool {
	if x != nil {
		return x.ShowPageAnimation
	}
	return false
}

type ContentInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 标题。
	Title string `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	// 内容。
	Content       string `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContentInfo) Reset() {
	*x = ContentInfo{}
	mi := &file_app_user_game_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContentInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContentInfo) ProtoMessage() {}

func (x *ContentInfo) ProtoReflect() protoreflect.Message {
	mi := &file_app_user_game_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContentInfo.ProtoReflect.Descriptor instead.
func (*ContentInfo) Descriptor() ([]byte, []int) {
	return file_app_user_game_proto_rawDescGZIP(), []int{3}
}

func (x *ContentInfo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ContentInfo) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type UserGameExpPrivilege struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 权益类型。
	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	// 权益描述。
	Desc string `protobuf:"bytes,2,opt,name=desc,proto3" json:"desc,omitempty"`
	// 权益值。
	Value         string `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserGameExpPrivilege) Reset() {
	*x = UserGameExpPrivilege{}
	mi := &file_app_user_game_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserGameExpPrivilege) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserGameExpPrivilege) ProtoMessage() {}

func (x *UserGameExpPrivilege) ProtoReflect() protoreflect.Message {
	mi := &file_app_user_game_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserGameExpPrivilege.ProtoReflect.Descriptor instead.
func (*UserGameExpPrivilege) Descriptor() ([]byte, []int) {
	return file_app_user_game_proto_rawDescGZIP(), []int{4}
}

func (x *UserGameExpPrivilege) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *UserGameExpPrivilege) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *UserGameExpPrivilege) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type SaveGameAnimationStatusRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 用户 ID。
	UserId string `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	// 设备 SN。
	Sn string `protobuf:"bytes,2,opt,name=sn,proto3" json:"sn,omitempty"`
	// 等级 ID。
	LevelId int32 `protobuf:"varint,3,opt,name=levelId,proto3" json:"levelId,omitempty"`
	// 平台类型。
	PlatformType int32 `protobuf:"varint,4,opt,name=platformType,proto3" json:"platformType,omitempty"`
	// App 版本号。
	AppVersion    string `protobuf:"bytes,5,opt,name=appVersion,proto3" json:"appVersion,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveGameAnimationStatusRequest) Reset() {
	*x = SaveGameAnimationStatusRequest{}
	mi := &file_app_user_game_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveGameAnimationStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveGameAnimationStatusRequest) ProtoMessage() {}

func (x *SaveGameAnimationStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_user_game_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveGameAnimationStatusRequest.ProtoReflect.Descriptor instead.
func (*SaveGameAnimationStatusRequest) Descriptor() ([]byte, []int) {
	return file_app_user_game_proto_rawDescGZIP(), []int{5}
}

func (x *SaveGameAnimationStatusRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SaveGameAnimationStatusRequest) GetSn() string {
	if x != nil {
		return x.Sn
	}
	return ""
}

func (x *SaveGameAnimationStatusRequest) GetLevelId() int32 {
	if x != nil {
		return x.LevelId
	}
	return 0
}

func (x *SaveGameAnimationStatusRequest) GetPlatformType() int32 {
	if x != nil {
		return x.PlatformType
	}
	return 0
}

func (x *SaveGameAnimationStatusRequest) GetAppVersion() string {
	if x != nil {
		return x.AppVersion
	}
	return ""
}

type SaveGameAnimationStatusResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 状态码：0 成功，其他失败。
	Status int32 `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	// 结果说明。
	Message       string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveGameAnimationStatusResponse) Reset() {
	*x = SaveGameAnimationStatusResponse{}
	mi := &file_app_user_game_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveGameAnimationStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveGameAnimationStatusResponse) ProtoMessage() {}

func (x *SaveGameAnimationStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_user_game_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveGameAnimationStatusResponse.ProtoReflect.Descriptor instead.
func (*SaveGameAnimationStatusResponse) Descriptor() ([]byte, []int) {
	return file_app_user_game_proto_rawDescGZIP(), []int{6}
}

func (x *SaveGameAnimationStatusResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *SaveGameAnimationStatusResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_app_user_game_proto protoreflect.FileDescriptor

const file_app_user_game_proto_rawDesc = "" +
	"\n" +
	"\x13app_user_game.proto\x12\busergame\"U\n" +
	"\x15GetUserGameExpRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05phone\x18\x02 \x01(\tR\x05phone\x12\x0e\n" +
	"\x02sn\x18\x03 \x01(\tR\x02sn\"y\n" +
	"\x16GetUserGameExpResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x05R\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12-\n" +
	"\x04data\x18\x03 \x01(\v2\x19.usergame.UserGameExpInfoR\x04data\"\xbd\x03\n" +
	"\x0fUserGameExpInfo\x12\x1c\n" +
	"\tlevelName\x18\x01 \x01(\tR\tlevelName\x12\x18\n" +
	"\alevelId\x18\x02 \x01(\x05R\alevelId\x12\x16\n" +
	"\x06curExp\x18\x03 \x01(\x05R\x06curExp\x12$\n" +
	"\rexpLeftToNext\x18\x04 \x01(\x05R\rexpLeftToNext\x12*\n" +
	"\x10curLevelTotalExp\x18\x05 \x01(\x05R\x10curLevelTotalExp\x12,\n" +
	"\x11nextPrivilegeText\x18\x06 \x03(\tR\x11nextPrivilegeText\x12/\n" +
	"\atipInfo\x18\a \x01(\v2\x15.usergame.ContentInfoR\atipInfo\x12>\n" +
	"\n" +
	"privileges\x18\b \x03(\v2\x1e.usergame.UserGameExpPrivilegeR\n" +
	"privileges\x12;\n" +
	"\rlevelPageText\x18\t \x01(\v2\x15.usergame.ContentInfoR\rlevelPageText\x12,\n" +
	"\x11showPageAnimation\x18\n" +
	" \x01(\bR\x11showPageAnimation\"=\n" +
	"\vContentInfo\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"T\n" +
	"\x14UserGameExpPrivilege\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x12\n" +
	"\x04desc\x18\x02 \x01(\tR\x04desc\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\"\xa6\x01\n" +
	"\x1eSaveGameAnimationStatusRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\tR\x06userId\x12\x0e\n" +
	"\x02sn\x18\x02 \x01(\tR\x02sn\x12\x18\n" +
	"\alevelId\x18\x03 \x01(\x05R\alevelId\x12\"\n" +
	"\fplatformType\x18\x04 \x01(\x05R\fplatformType\x12\x1e\n" +
	"\n" +
	"appVersion\x18\x05 \x01(\tR\n" +
	"appVersion\"S\n" +
	"\x1fSaveGameAnimationStatusResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x05R\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xd6\x01\n" +
	"\x0fUserGameService\x12S\n" +
	"\x0eGetUserGameExp\x12\x1f.usergame.GetUserGameExpRequest\x1a .usergame.GetUserGameExpResponse\x12n\n" +
	"\x17SaveGameAnimationStatus\x12(.usergame.SaveGameAnimationStatusRequest\x1a).usergame.SaveGameAnimationStatusResponseB\x1cZ\x1aservice//usergame;usergameb\x06proto3"

var (
	file_app_user_game_proto_rawDescOnce sync.Once
	file_app_user_game_proto_rawDescData []byte
)

func file_app_user_game_proto_rawDescGZIP() []byte {
	file_app_user_game_proto_rawDescOnce.Do(func() {
		file_app_user_game_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_app_user_game_proto_rawDesc), len(file_app_user_game_proto_rawDesc)))
	})
	return file_app_user_game_proto_rawDescData
}

var file_app_user_game_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_app_user_game_proto_goTypes = []any{
	(*GetUserGameExpRequest)(nil),           // 0: usergame.GetUserGameExpRequest
	(*GetUserGameExpResponse)(nil),          // 1: usergame.GetUserGameExpResponse
	(*UserGameExpInfo)(nil),                 // 2: usergame.UserGameExpInfo
	(*ContentInfo)(nil),                     // 3: usergame.ContentInfo
	(*UserGameExpPrivilege)(nil),            // 4: usergame.UserGameExpPrivilege
	(*SaveGameAnimationStatusRequest)(nil),  // 5: usergame.SaveGameAnimationStatusRequest
	(*SaveGameAnimationStatusResponse)(nil), // 6: usergame.SaveGameAnimationStatusResponse
}
var file_app_user_game_proto_depIdxs = []int32{
	2, // 0: usergame.GetUserGameExpResponse.data:type_name -> usergame.UserGameExpInfo
	3, // 1: usergame.UserGameExpInfo.tipInfo:type_name -> usergame.ContentInfo
	4, // 2: usergame.UserGameExpInfo.privileges:type_name -> usergame.UserGameExpPrivilege
	3, // 3: usergame.UserGameExpInfo.levelPageText:type_name -> usergame.ContentInfo
	0, // 4: usergame.UserGameService.GetUserGameExp:input_type -> usergame.GetUserGameExpRequest
	5, // 5: usergame.UserGameService.SaveGameAnimationStatus:input_type -> usergame.SaveGameAnimationStatusRequest
	1, // 6: usergame.UserGameService.GetUserGameExp:output_type -> usergame.GetUserGameExpResponse
	6, // 7: usergame.UserGameService.SaveGameAnimationStatus:output_type -> usergame.SaveGameAnimationStatusResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_app_user_game_proto_init() }
func file_app_user_game_proto_init() {
	if File_app_user_game_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_app_user_game_proto_rawDesc), len(file_app_user_game_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_app_user_game_proto_goTypes,
		DependencyIndexes: file_app_user_game_proto_depIdxs,
		MessageInfos:      file_app_user_game_proto_msgTypes,
	}.Build()
	File_app_user_game_proto = out.File
	file_app_user_game_proto_goTypes = nil
	file_app_user_game_proto_depIdxs = nil
}
