// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.29.3
// source: app_user_game.proto

package usergame

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UserGameService_GetUserGameExp_FullMethodName          = "/usergame.UserGameService/GetUserGameExp"
	UserGameService_SaveGameAnimationStatus_FullMethodName = "/usergame.UserGameService/SaveGameAnimationStatus"
)

// UserGameServiceClient is the client API for UserGameService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserGameServiceClient interface {
	// 查询用户游戏化等级与经验信息。
	GetUserGameExp(ctx context.Context, in *GetUserGameExpRequest, opts ...grpc.CallOption) (*GetUserGameExpResponse, error)
	// 保存游戏页面动效展示状态。
	SaveGameAnimationStatus(ctx context.Context, in *SaveGameAnimationStatusRequest, opts ...grpc.CallOption) (*SaveGameAnimationStatusResponse, error)
}

type userGameServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserGameServiceClient(cc grpc.ClientConnInterface) UserGameServiceClient {
	return &userGameServiceClient{cc}
}

func (c *userGameServiceClient) GetUserGameExp(ctx context.Context, in *GetUserGameExpRequest, opts ...grpc.CallOption) (*GetUserGameExpResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserGameExpResponse)
	err := c.cc.Invoke(ctx, UserGameService_GetUserGameExp_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userGameServiceClient) SaveGameAnimationStatus(ctx context.Context, in *SaveGameAnimationStatusRequest, opts ...grpc.CallOption) (*SaveGameAnimationStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveGameAnimationStatusResponse)
	err := c.cc.Invoke(ctx, UserGameService_SaveGameAnimationStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserGameServiceServer is the server API for UserGameService service.
// All implementations must embed UnimplementedUserGameServiceServer
// for forward compatibility.
type UserGameServiceServer interface {
	// 查询用户游戏化等级与经验信息。
	GetUserGameExp(context.Context, *GetUserGameExpRequest) (*GetUserGameExpResponse, error)
	// 保存游戏页面动效展示状态。
	SaveGameAnimationStatus(context.Context, *SaveGameAnimationStatusRequest) (*SaveGameAnimationStatusResponse, error)
	mustEmbedUnimplementedUserGameServiceServer()
}

// UnimplementedUserGameServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUserGameServiceServer struct{}

func (UnimplementedUserGameServiceServer) GetUserGameExp(context.Context, *GetUserGameExpRequest) (*GetUserGameExpResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserGameExp not implemented")
}
func (UnimplementedUserGameServiceServer) SaveGameAnimationStatus(context.Context, *SaveGameAnimationStatusRequest) (*SaveGameAnimationStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SaveGameAnimationStatus not implemented")
}
func (UnimplementedUserGameServiceServer) mustEmbedUnimplementedUserGameServiceServer() {}
func (UnimplementedUserGameServiceServer) testEmbeddedByValue()                         {}

// UnsafeUserGameServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserGameServiceServer will
// result in compilation errors.
type UnsafeUserGameServiceServer interface {
	mustEmbedUnimplementedUserGameServiceServer()
}

func RegisterUserGameServiceServer(s grpc.ServiceRegistrar, srv UserGameServiceServer) {
	// If the following call panics, it indicates UnimplementedUserGameServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UserGameService_ServiceDesc, srv)
}

func _UserGameService_GetUserGameExp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserGameExpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserGameServiceServer).GetUserGameExp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserGameService_GetUserGameExp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserGameServiceServer).GetUserGameExp(ctx, req.(*GetUserGameExpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserGameService_SaveGameAnimationStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveGameAnimationStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserGameServiceServer).SaveGameAnimationStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserGameService_SaveGameAnimationStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserGameServiceServer).SaveGameAnimationStatus(ctx, req.(*SaveGameAnimationStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UserGameService_ServiceDesc is the grpc.ServiceDesc for UserGameService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserGameService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "usergame.UserGameService",
	HandlerType: (*UserGameServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUserGameExp",
			Handler:    _UserGameService_GetUserGameExp_Handler,
		},
		{
			MethodName: "SaveGameAnimationStatus",
			Handler:    _UserGameService_SaveGameAnimationStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "app_user_game.proto",
}
