// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: task_call.proto

package taskcall

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CallTaskRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 任务名称，用于标识需要执行的任务逻辑。
	TaskName string `protobuf:"bytes,1,opt,name=taskName,proto3" json:"taskName,omitempty"`
	// JSON 字符串参数，由具体任务按约定解析。
	Params        string `protobuf:"bytes,2,opt,name=params,proto3" json:"params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallTaskRequest) Reset() {
	*x = CallTaskRequest{}
	mi := &file_task_call_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallTaskRequest) ProtoMessage() {}

func (x *CallTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_call_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallTaskRequest.ProtoReflect.Descriptor instead.
func (*CallTaskRequest) Descriptor() ([]byte, []int) {
	return file_task_call_proto_rawDescGZIP(), []int{0}
}

func (x *CallTaskRequest) GetTaskName() string {
	if x != nil {
		return x.TaskName
	}
	return ""
}

func (x *CallTaskRequest) GetParams() string {
	if x != nil {
		return x.Params
	}
	return ""
}

type CallTaskResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 状态码：0 成功，其他失败。
	Status int32 `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	// 结果说明。
	Message       string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallTaskResponse) Reset() {
	*x = CallTaskResponse{}
	mi := &file_task_call_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallTaskResponse) ProtoMessage() {}

func (x *CallTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_task_call_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallTaskResponse.ProtoReflect.Descriptor instead.
func (*CallTaskResponse) Descriptor() ([]byte, []int) {
	return file_task_call_proto_rawDescGZIP(), []int{1}
}

func (x *CallTaskResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *CallTaskResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_task_call_proto protoreflect.FileDescriptor

const file_task_call_proto_rawDesc = "" +
	"\n" +
	"\x0ftask_call.proto\x12\btaskcall\"E\n" +
	"\x0fCallTaskRequest\x12\x1a\n" +
	"\btaskName\x18\x01 \x01(\tR\btaskName\x12\x16\n" +
	"\x06params\x18\x02 \x01(\tR\x06params\"D\n" +
	"\x10CallTaskResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x05R\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2T\n" +
	"\x0fTaskCallService\x12A\n" +
	"\bCallTask\x12\x19.taskcall.CallTaskRequest\x1a\x1a.taskcall.CallTaskResponseB\x19Z\x17service//tasks;taskcallb\x06proto3"

var (
	file_task_call_proto_rawDescOnce sync.Once
	file_task_call_proto_rawDescData []byte
)

func file_task_call_proto_rawDescGZIP() []byte {
	file_task_call_proto_rawDescOnce.Do(func() {
		file_task_call_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_task_call_proto_rawDesc), len(file_task_call_proto_rawDesc)))
	})
	return file_task_call_proto_rawDescData
}

var file_task_call_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_task_call_proto_goTypes = []any{
	(*CallTaskRequest)(nil),  // 0: taskcall.CallTaskRequest
	(*CallTaskResponse)(nil), // 1: taskcall.CallTaskResponse
}
var file_task_call_proto_depIdxs = []int32{
	0, // 0: taskcall.TaskCallService.CallTask:input_type -> taskcall.CallTaskRequest
	1, // 1: taskcall.TaskCallService.CallTask:output_type -> taskcall.CallTaskResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_task_call_proto_init() }
func file_task_call_proto_init() {
	if File_task_call_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_task_call_proto_rawDesc), len(file_task_call_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_task_call_proto_goTypes,
		DependencyIndexes: file_task_call_proto_depIdxs,
		MessageInfos:      file_task_call_proto_msgTypes,
	}.Build()
	File_task_call_proto = out.File
	file_task_call_proto_goTypes = nil
	file_task_call_proto_depIdxs = nil
}
