// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.29.3
// source: task_call.proto

package taskcall

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TaskCallService_CallTask_FullMethodName = "/taskcall.TaskCallService/CallTask"
)

// TaskCallServiceClient is the client API for TaskCallService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TaskCallServiceClient interface {
	// 提供被定时任务调用的方法，在其他服务中通过定时任务调用对应逻辑。
	CallTask(ctx context.Context, in *CallTaskRequest, opts ...grpc.CallOption) (*CallTaskResponse, error)
}

type taskCallServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTaskCallServiceClient(cc grpc.ClientConnInterface) TaskCallServiceClient {
	return &taskCallServiceClient{cc}
}

func (c *taskCallServiceClient) CallTask(ctx context.Context, in *CallTaskRequest, opts ...grpc.CallOption) (*CallTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CallTaskResponse)
	err := c.cc.Invoke(ctx, TaskCallService_CallTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TaskCallServiceServer is the server API for TaskCallService service.
// All implementations must embed UnimplementedTaskCallServiceServer
// for forward compatibility.
type TaskCallServiceServer interface {
	// 提供被定时任务调用的方法，在其他服务中通过定时任务调用对应逻辑。
	CallTask(context.Context, *CallTaskRequest) (*CallTaskResponse, error)
	mustEmbedUnimplementedTaskCallServiceServer()
}

// UnimplementedTaskCallServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTaskCallServiceServer struct{}

func (UnimplementedTaskCallServiceServer) CallTask(context.Context, *CallTaskRequest) (*CallTaskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CallTask not implemented")
}
func (UnimplementedTaskCallServiceServer) mustEmbedUnimplementedTaskCallServiceServer() {}
func (UnimplementedTaskCallServiceServer) testEmbeddedByValue()                         {}

// UnsafeTaskCallServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TaskCallServiceServer will
// result in compilation errors.
type UnsafeTaskCallServiceServer interface {
	mustEmbedUnimplementedTaskCallServiceServer()
}

func RegisterTaskCallServiceServer(s grpc.ServiceRegistrar, srv TaskCallServiceServer) {
	// If the following call panics, it indicates UnimplementedTaskCallServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TaskCallService_ServiceDesc, srv)
}

func _TaskCallService_CallTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CallTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskCallServiceServer).CallTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskCallService_CallTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskCallServiceServer).CallTask(ctx, req.(*CallTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TaskCallService_ServiceDesc is the grpc.ServiceDesc for TaskCallService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TaskCallService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "taskcall.TaskCallService",
	HandlerType: (*TaskCallServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CallTask",
			Handler:    _TaskCallService_CallTask_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "task_call.proto",
}
