// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: user_and_device_query.proto

package basicquery

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QueryDeviceBindInfoRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 设备 ID，与 deviceSn 至少填写一个。
	DeviceId string `protobuf:"bytes,1,opt,name=deviceId,proto3" json:"deviceId,omitempty"`
	// 设备 SN，与 deviceId 至少填写一个。
	DeviceSn string `protobuf:"bytes,2,opt,name=deviceSn,proto3" json:"deviceSn,omitempty"`
	// 用户手机号。
	Phone         string `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryDeviceBindInfoRequest) Reset() {
	*x = QueryDeviceBindInfoRequest{}
	mi := &file_user_and_device_query_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryDeviceBindInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryDeviceBindInfoRequest) ProtoMessage() {}

func (x *QueryDeviceBindInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_and_device_query_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryDeviceBindInfoRequest.ProtoReflect.Descriptor instead.
func (*QueryDeviceBindInfoRequest) Descriptor() ([]byte, []int) {
	return file_user_and_device_query_proto_rawDescGZIP(), []int{0}
}

func (x *QueryDeviceBindInfoRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *QueryDeviceBindInfoRequest) GetDeviceSn() string {
	if x != nil {
		return x.DeviceSn
	}
	return ""
}

func (x *QueryDeviceBindInfoRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

type QueryDeviceBindInfoResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 状态码：0 成功，其他失败。
	Status int32 `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	// 结果说明。
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// 设备绑定信息。
	Data          *DeviceBindInfo `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryDeviceBindInfoResponse) Reset() {
	*x = QueryDeviceBindInfoResponse{}
	mi := &file_user_and_device_query_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryDeviceBindInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryDeviceBindInfoResponse) ProtoMessage() {}

func (x *QueryDeviceBindInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_and_device_query_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryDeviceBindInfoResponse.ProtoReflect.Descriptor instead.
func (*QueryDeviceBindInfoResponse) Descriptor() ([]byte, []int) {
	return file_user_and_device_query_proto_rawDescGZIP(), []int{1}
}

func (x *QueryDeviceBindInfoResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *QueryDeviceBindInfoResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *QueryDeviceBindInfoResponse) GetData() *DeviceBindInfo {
	if x != nil {
		return x.Data
	}
	return nil
}

type DeviceBindInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 绑定记录 ID。
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// 用户 ID。
	UserId string `protobuf:"bytes,2,opt,name=userId,proto3" json:"userId,omitempty"`
	// 用户手机号。
	Phone string `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	// 设备 SN。
	DeviceSn string `protobuf:"bytes,4,opt,name=deviceSn,proto3" json:"deviceSn,omitempty"`
	// 设备 ID。
	DeviceId string `protobuf:"bytes,5,opt,name=deviceId,proto3" json:"deviceId,omitempty"`
	// 设备别名。
	DeviceAlias string `protobuf:"bytes,6,opt,name=deviceAlias,proto3" json:"deviceAlias,omitempty"`
	// 绑定角色。
	Role int32 `protobuf:"varint,7,opt,name=role,proto3" json:"role,omitempty"`
	// 绑定状态。
	BindStatus int32 `protobuf:"varint,8,opt,name=bindStatus,proto3" json:"bindStatus,omitempty"`
	// 绑定时间戳，毫秒。
	BindTime int64 `protobuf:"varint,9,opt,name=bindTime,proto3" json:"bindTime,omitempty"`
	// 解绑时间戳，毫秒。
	UnbindTime    int64 `protobuf:"varint,10,opt,name=unbindTime,proto3" json:"unbindTime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceBindInfo) Reset() {
	*x = DeviceBindInfo{}
	mi := &file_user_and_device_query_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceBindInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceBindInfo) ProtoMessage() {}

func (x *DeviceBindInfo) ProtoReflect() protoreflect.Message {
	mi := &file_user_and_device_query_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceBindInfo.ProtoReflect.Descriptor instead.
func (*DeviceBindInfo) Descriptor() ([]byte, []int) {
	return file_user_and_device_query_proto_rawDescGZIP(), []int{2}
}

func (x *DeviceBindInfo) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DeviceBindInfo) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DeviceBindInfo) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *DeviceBindInfo) GetDeviceSn() string {
	if x != nil {
		return x.DeviceSn
	}
	return ""
}

func (x *DeviceBindInfo) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *DeviceBindInfo) GetDeviceAlias() string {
	if x != nil {
		return x.DeviceAlias
	}
	return ""
}

func (x *DeviceBindInfo) GetRole() int32 {
	if x != nil {
		return x.Role
	}
	return 0
}

func (x *DeviceBindInfo) GetBindStatus() int32 {
	if x != nil {
		return x.BindStatus
	}
	return 0
}

func (x *DeviceBindInfo) GetBindTime() int64 {
	if x != nil {
		return x.BindTime
	}
	return 0
}

func (x *DeviceBindInfo) GetUnbindTime() int64 {
	if x != nil {
		return x.UnbindTime
	}
	return 0
}

type QueryUserBasicInfoRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 用户手机号。
	Phone         string `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryUserBasicInfoRequest) Reset() {
	*x = QueryUserBasicInfoRequest{}
	mi := &file_user_and_device_query_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryUserBasicInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryUserBasicInfoRequest) ProtoMessage() {}

func (x *QueryUserBasicInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_and_device_query_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryUserBasicInfoRequest.ProtoReflect.Descriptor instead.
func (*QueryUserBasicInfoRequest) Descriptor() ([]byte, []int) {
	return file_user_and_device_query_proto_rawDescGZIP(), []int{3}
}

func (x *QueryUserBasicInfoRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

type QueryUserBasicInfoResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 状态码：0 成功，其他失败。
	Status int32 `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	// 结果说明。
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// 用户基础信息。
	Data          *UserBasicInfo `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryUserBasicInfoResponse) Reset() {
	*x = QueryUserBasicInfoResponse{}
	mi := &file_user_and_device_query_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryUserBasicInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryUserBasicInfoResponse) ProtoMessage() {}

func (x *QueryUserBasicInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_and_device_query_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryUserBasicInfoResponse.ProtoReflect.Descriptor instead.
func (*QueryUserBasicInfoResponse) Descriptor() ([]byte, []int) {
	return file_user_and_device_query_proto_rawDescGZIP(), []int{4}
}

func (x *QueryUserBasicInfoResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *QueryUserBasicInfoResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *QueryUserBasicInfoResponse) GetData() *UserBasicInfo {
	if x != nil {
		return x.Data
	}
	return nil
}

type UserBasicInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 用户记录 ID。
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// 用户 ID。
	UserId string `protobuf:"bytes,2,opt,name=userId,proto3" json:"userId,omitempty"`
	// 用户手机号。
	Phone string `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	// 昵称。
	Nickname string `protobuf:"bytes,4,opt,name=nickname,proto3" json:"nickname,omitempty"`
	// 姓名。
	Name string `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	// 头像地址。
	AvatarUrl string `protobuf:"bytes,6,opt,name=avatarUrl,proto3" json:"avatarUrl,omitempty"`
	// 用户标签。
	UserTag string `protobuf:"bytes,7,opt,name=userTag,proto3" json:"userTag,omitempty"`
	// 项目名称。
	ProjectName string `protobuf:"bytes,8,opt,name=projectName,proto3" json:"projectName,omitempty"`
	// 邮箱。
	Email string `protobuf:"bytes,9,opt,name=email,proto3" json:"email,omitempty"`
	// 性别。
	Gender int32 `protobuf:"varint,10,opt,name=gender,proto3" json:"gender,omitempty"`
	// 关注权限。
	FollowPermission int32 `protobuf:"varint,11,opt,name=followPermission,proto3" json:"followPermission,omitempty"`
	// 用户状态。
	Status        int32 `protobuf:"varint,12,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserBasicInfo) Reset() {
	*x = UserBasicInfo{}
	mi := &file_user_and_device_query_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserBasicInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserBasicInfo) ProtoMessage() {}

func (x *UserBasicInfo) ProtoReflect() protoreflect.Message {
	mi := &file_user_and_device_query_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserBasicInfo.ProtoReflect.Descriptor instead.
func (*UserBasicInfo) Descriptor() ([]byte, []int) {
	return file_user_and_device_query_proto_rawDescGZIP(), []int{5}
}

func (x *UserBasicInfo) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserBasicInfo) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserBasicInfo) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *UserBasicInfo) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *UserBasicInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserBasicInfo) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *UserBasicInfo) GetUserTag() string {
	if x != nil {
		return x.UserTag
	}
	return ""
}

func (x *UserBasicInfo) GetProjectName() string {
	if x != nil {
		return x.ProjectName
	}
	return ""
}

func (x *UserBasicInfo) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserBasicInfo) GetGender() int32 {
	if x != nil {
		return x.Gender
	}
	return 0
}

func (x *UserBasicInfo) GetFollowPermission() int32 {
	if x != nil {
		return x.FollowPermission
	}
	return 0
}

func (x *UserBasicInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type QueryDeviceGrowthSummaryRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 用户手机号。
	Phone string `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	// 设备 SN。
	Sn            string `protobuf:"bytes,2,opt,name=sn,proto3" json:"sn,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryDeviceGrowthSummaryRequest) Reset() {
	*x = QueryDeviceGrowthSummaryRequest{}
	mi := &file_user_and_device_query_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryDeviceGrowthSummaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryDeviceGrowthSummaryRequest) ProtoMessage() {}

func (x *QueryDeviceGrowthSummaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_and_device_query_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryDeviceGrowthSummaryRequest.ProtoReflect.Descriptor instead.
func (*QueryDeviceGrowthSummaryRequest) Descriptor() ([]byte, []int) {
	return file_user_and_device_query_proto_rawDescGZIP(), []int{6}
}

func (x *QueryDeviceGrowthSummaryRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *QueryDeviceGrowthSummaryRequest) GetSn() string {
	if x != nil {
		return x.Sn
	}
	return ""
}

type QueryDeviceGrowthSummaryResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 状态码：0 成功，其他失败。
	Status int32 `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	// 结果说明。
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// 设备成长监控数据。
	Data          *DeviceGrowthSummary `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryDeviceGrowthSummaryResponse) Reset() {
	*x = QueryDeviceGrowthSummaryResponse{}
	mi := &file_user_and_device_query_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryDeviceGrowthSummaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryDeviceGrowthSummaryResponse) ProtoMessage() {}

func (x *QueryDeviceGrowthSummaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_and_device_query_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryDeviceGrowthSummaryResponse.ProtoReflect.Descriptor instead.
func (*QueryDeviceGrowthSummaryResponse) Descriptor() ([]byte, []int) {
	return file_user_and_device_query_proto_rawDescGZIP(), []int{7}
}

func (x *QueryDeviceGrowthSummaryResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *QueryDeviceGrowthSummaryResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *QueryDeviceGrowthSummaryResponse) GetData() *DeviceGrowthSummary {
	if x != nil {
		return x.Data
	}
	return nil
}

type DeviceGrowthSummary struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 设备 SN。
	Sn string `protobuf:"bytes,1,opt,name=sn,proto3" json:"sn,omitempty"`
	// 成长指标列表（duration / duration_str / mileage / interactions）。
	Info          []*DeviceGrowthSummaryItem `protobuf:"bytes,2,rep,name=info,proto3" json:"info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceGrowthSummary) Reset() {
	*x = DeviceGrowthSummary{}
	mi := &file_user_and_device_query_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceGrowthSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceGrowthSummary) ProtoMessage() {}

func (x *DeviceGrowthSummary) ProtoReflect() protoreflect.Message {
	mi := &file_user_and_device_query_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceGrowthSummary.ProtoReflect.Descriptor instead.
func (*DeviceGrowthSummary) Descriptor() ([]byte, []int) {
	return file_user_and_device_query_proto_rawDescGZIP(), []int{8}
}

func (x *DeviceGrowthSummary) GetSn() string {
	if x != nil {
		return x.Sn
	}
	return ""
}

func (x *DeviceGrowthSummary) GetInfo() []*DeviceGrowthSummaryItem {
	if x != nil {
		return x.Info
	}
	return nil
}

type DeviceGrowthSummaryItem struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 指标名称。
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// 数值型累计值（duration / mileage / interactions）。
	TotalNumber float64 `protobuf:"fixed64,2,opt,name=totalNumber,proto3" json:"totalNumber,omitempty"`
	// 数值型当日值（duration / mileage / interactions）。
	TodayNumber float64 `protobuf:"fixed64,3,opt,name=todayNumber,proto3" json:"todayNumber,omitempty"`
	// 文本型累计值（duration_str）。
	TotalText string `protobuf:"bytes,4,opt,name=totalText,proto3" json:"totalText,omitempty"`
	// 文本型当日值（duration_str）。
	TodayText     string `protobuf:"bytes,5,opt,name=todayText,proto3" json:"todayText,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceGrowthSummaryItem) Reset() {
	*x = DeviceGrowthSummaryItem{}
	mi := &file_user_and_device_query_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceGrowthSummaryItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceGrowthSummaryItem) ProtoMessage() {}

func (x *DeviceGrowthSummaryItem) ProtoReflect() protoreflect.Message {
	mi := &file_user_and_device_query_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceGrowthSummaryItem.ProtoReflect.Descriptor instead.
func (*DeviceGrowthSummaryItem) Descriptor() ([]byte, []int) {
	return file_user_and_device_query_proto_rawDescGZIP(), []int{9}
}

func (x *DeviceGrowthSummaryItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DeviceGrowthSummaryItem) GetTotalNumber() float64 {
	if x != nil {
		return x.TotalNumber
	}
	return 0
}

func (x *DeviceGrowthSummaryItem) GetTodayNumber() float64 {
	if x != nil {
		return x.TodayNumber
	}
	return 0
}

func (x *DeviceGrowthSummaryItem) GetTotalText() string {
	if x != nil {
		return x.TotalText
	}
	return ""
}

func (x *DeviceGrowthSummaryItem) GetTodayText() string {
	if x != nil {
		return x.TodayText
	}
	return ""
}

var File_user_and_device_query_proto protoreflect.FileDescriptor

const file_user_and_device_query_proto_rawDesc = "" +
	"\n" +
	"\x1buser_and_device_query.proto\x12\n" +
	"basicquery\"j\n" +
	"\x1aQueryDeviceBindInfoRequest\x12\x1a\n" +
	"\bdeviceId\x18\x01 \x01(\tR\bdeviceId\x12\x1a\n" +
	"\bdeviceSn\x18\x02 \x01(\tR\bdeviceSn\x12\x14\n" +
	"\x05phone\x18\x03 \x01(\tR\x05phone\"\x7f\n" +
	"\x1bQueryDeviceBindInfoResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x05R\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12.\n" +
	"\x04data\x18\x03 \x01(\v2\x1a.basicquery.DeviceBindInfoR\x04data\"\x98\x02\n" +
	"\x0eDeviceBindInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\tR\x06userId\x12\x14\n" +
	"\x05phone\x18\x03 \x01(\tR\x05phone\x12\x1a\n" +
	"\bdeviceSn\x18\x04 \x01(\tR\bdeviceSn\x12\x1a\n" +
	"\bdeviceId\x18\x05 \x01(\tR\bdeviceId\x12 \n" +
	"\vdeviceAlias\x18\x06 \x01(\tR\vdeviceAlias\x12\x12\n" +
	"\x04role\x18\a \x01(\x05R\x04role\x12\x1e\n" +
	"\n" +
	"bindStatus\x18\b \x01(\x05R\n" +
	"bindStatus\x12\x1a\n" +
	"\bbindTime\x18\t \x01(\x03R\bbindTime\x12\x1e\n" +
	"\n" +
	"unbindTime\x18\n" +
	" \x01(\x03R\n" +
	"unbindTime\"1\n" +
	"\x19QueryUserBasicInfoRequest\x12\x14\n" +
	"\x05phone\x18\x01 \x01(\tR\x05phone\"}\n" +
	"\x1aQueryUserBasicInfoResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x05R\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12-\n" +
	"\x04data\x18\x03 \x01(\v2\x19.basicquery.UserBasicInfoR\x04data\"\xc9\x02\n" +
	"\rUserBasicInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\tR\x06userId\x12\x14\n" +
	"\x05phone\x18\x03 \x01(\tR\x05phone\x12\x1a\n" +
	"\bnickname\x18\x04 \x01(\tR\bnickname\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\x12\x1c\n" +
	"\tavatarUrl\x18\x06 \x01(\tR\tavatarUrl\x12\x18\n" +
	"\auserTag\x18\a \x01(\tR\auserTag\x12 \n" +
	"\vprojectName\x18\b \x01(\tR\vprojectName\x12\x14\n" +
	"\x05email\x18\t \x01(\tR\x05email\x12\x16\n" +
	"\x06gender\x18\n" +
	" \x01(\x05R\x06gender\x12*\n" +
	"\x10followPermission\x18\v \x01(\x05R\x10followPermission\x12\x16\n" +
	"\x06status\x18\f \x01(\x05R\x06status\"G\n" +
	"\x1fQueryDeviceGrowthSummaryRequest\x12\x14\n" +
	"\x05phone\x18\x01 \x01(\tR\x05phone\x12\x0e\n" +
	"\x02sn\x18\x02 \x01(\tR\x02sn\"\x89\x01\n" +
	" QueryDeviceGrowthSummaryResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x05R\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x123\n" +
	"\x04data\x18\x03 \x01(\v2\x1f.basicquery.DeviceGrowthSummaryR\x04data\"^\n" +
	"\x13DeviceGrowthSummary\x12\x0e\n" +
	"\x02sn\x18\x01 \x01(\tR\x02sn\x127\n" +
	"\x04info\x18\x02 \x03(\v2#.basicquery.DeviceGrowthSummaryItemR\x04info\"\xad\x01\n" +
	"\x17DeviceGrowthSummaryItem\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vtotalNumber\x18\x02 \x01(\x01R\vtotalNumber\x12 \n" +
	"\vtodayNumber\x18\x03 \x01(\x01R\vtodayNumber\x12\x1c\n" +
	"\ttotalText\x18\x04 \x01(\tR\ttotalText\x12\x1c\n" +
	"\ttodayText\x18\x05 \x01(\tR\ttodayText2\xdf\x02\n" +
	"\x19UserAndDeviceQueryService\x12f\n" +
	"\x13QueryDeviceBindInfo\x12&.basicquery.QueryDeviceBindInfoRequest\x1a'.basicquery.QueryDeviceBindInfoResponse\x12c\n" +
	"\x12QueryUserBasicInfo\x12%.basicquery.QueryUserBasicInfoRequest\x1a&.basicquery.QueryUserBasicInfoResponse\x12u\n" +
	"\x18QueryDeviceGrowthSummary\x12+.basicquery.QueryDeviceGrowthSummaryRequest\x1a,.basicquery.QueryDeviceGrowthSummaryResponseB\x1bZ\x19service//basic;basicqueryb\x06proto3"

var (
	file_user_and_device_query_proto_rawDescOnce sync.Once
	file_user_and_device_query_proto_rawDescData []byte
)

func file_user_and_device_query_proto_rawDescGZIP() []byte {
	file_user_and_device_query_proto_rawDescOnce.Do(func() {
		file_user_and_device_query_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_and_device_query_proto_rawDesc), len(file_user_and_device_query_proto_rawDesc)))
	})
	return file_user_and_device_query_proto_rawDescData
}

var file_user_and_device_query_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_user_and_device_query_proto_goTypes = []any{
	(*QueryDeviceBindInfoRequest)(nil),       // 0: basicquery.QueryDeviceBindInfoRequest
	(*QueryDeviceBindInfoResponse)(nil),      // 1: basicquery.QueryDeviceBindInfoResponse
	(*DeviceBindInfo)(nil),                   // 2: basicquery.DeviceBindInfo
	(*QueryUserBasicInfoRequest)(nil),        // 3: basicquery.QueryUserBasicInfoRequest
	(*QueryUserBasicInfoResponse)(nil),       // 4: basicquery.QueryUserBasicInfoResponse
	(*UserBasicInfo)(nil),                    // 5: basicquery.UserBasicInfo
	(*QueryDeviceGrowthSummaryRequest)(nil),  // 6: basicquery.QueryDeviceGrowthSummaryRequest
	(*QueryDeviceGrowthSummaryResponse)(nil), // 7: basicquery.QueryDeviceGrowthSummaryResponse
	(*DeviceGrowthSummary)(nil),              // 8: basicquery.DeviceGrowthSummary
	(*DeviceGrowthSummaryItem)(nil),          // 9: basicquery.DeviceGrowthSummaryItem
}
var file_user_and_device_query_proto_depIdxs = []int32{
	2, // 0: basicquery.QueryDeviceBindInfoResponse.data:type_name -> basicquery.DeviceBindInfo
	5, // 1: basicquery.QueryUserBasicInfoResponse.data:type_name -> basicquery.UserBasicInfo
	8, // 2: basicquery.QueryDeviceGrowthSummaryResponse.data:type_name -> basicquery.DeviceGrowthSummary
	9, // 3: basicquery.DeviceGrowthSummary.info:type_name -> basicquery.DeviceGrowthSummaryItem
	0, // 4: basicquery.UserAndDeviceQueryService.QueryDeviceBindInfo:input_type -> basicquery.QueryDeviceBindInfoRequest
	3, // 5: basicquery.UserAndDeviceQueryService.QueryUserBasicInfo:input_type -> basicquery.QueryUserBasicInfoRequest
	6, // 6: basicquery.UserAndDeviceQueryService.QueryDeviceGrowthSummary:input_type -> basicquery.QueryDeviceGrowthSummaryRequest
	1, // 7: basicquery.UserAndDeviceQueryService.QueryDeviceBindInfo:output_type -> basicquery.QueryDeviceBindInfoResponse
	4, // 8: basicquery.UserAndDeviceQueryService.QueryUserBasicInfo:output_type -> basicquery.QueryUserBasicInfoResponse
	7, // 9: basicquery.UserAndDeviceQueryService.QueryDeviceGrowthSummary:output_type -> basicquery.QueryDeviceGrowthSummaryResponse
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_user_and_device_query_proto_init() }
func file_user_and_device_query_proto_init() {
	if File_user_and_device_query_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_and_device_query_proto_rawDesc), len(file_user_and_device_query_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_and_device_query_proto_goTypes,
		DependencyIndexes: file_user_and_device_query_proto_depIdxs,
		MessageInfos:      file_user_and_device_query_proto_msgTypes,
	}.Build()
	File_user_and_device_query_proto = out.File
	file_user_and_device_query_proto_goTypes = nil
	file_user_and_device_query_proto_depIdxs = nil
}
