// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.29.3
// source: user_and_device_query.proto

package basicquery

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UserAndDeviceQueryService_QueryDeviceBindInfo_FullMethodName = "/basicquery.UserAndDeviceQueryService/QueryDeviceBindInfo"
	UserAndDeviceQueryService_QueryUserBasicInfo_FullMethodName  = "/basicquery.UserAndDeviceQueryService/QueryUserBasicInfo"
)

// UserAndDeviceQueryServiceClient is the client API for UserAndDeviceQueryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserAndDeviceQueryServiceClient interface {
	// 按设备 ID 或 SN 与手机号查询设备绑定信息及设备别名。
	QueryDeviceBindInfo(ctx context.Context, in *QueryDeviceBindInfoRequest, opts ...grpc.CallOption) (*QueryDeviceBindInfoResponse, error)
	// 按手机号查询用户基础信息。
	QueryUserBasicInfo(ctx context.Context, in *QueryUserBasicInfoRequest, opts ...grpc.CallOption) (*QueryUserBasicInfoResponse, error)
}

type userAndDeviceQueryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserAndDeviceQueryServiceClient(cc grpc.ClientConnInterface) UserAndDeviceQueryServiceClient {
	return &userAndDeviceQueryServiceClient{cc}
}

func (c *userAndDeviceQueryServiceClient) QueryDeviceBindInfo(ctx context.Context, in *QueryDeviceBindInfoRequest, opts ...grpc.CallOption) (*QueryDeviceBindInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryDeviceBindInfoResponse)
	err := c.cc.Invoke(ctx, UserAndDeviceQueryService_QueryDeviceBindInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userAndDeviceQueryServiceClient) QueryUserBasicInfo(ctx context.Context, in *QueryUserBasicInfoRequest, opts ...grpc.CallOption) (*QueryUserBasicInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryUserBasicInfoResponse)
	err := c.cc.Invoke(ctx, UserAndDeviceQueryService_QueryUserBasicInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserAndDeviceQueryServiceServer is the server API for UserAndDeviceQueryService service.
// All implementations must embed UnimplementedUserAndDeviceQueryServiceServer
// for forward compatibility.
type UserAndDeviceQueryServiceServer interface {
	// 按设备 ID 或 SN 与手机号查询设备绑定信息及设备别名。
	QueryDeviceBindInfo(context.Context, *QueryDeviceBindInfoRequest) (*QueryDeviceBindInfoResponse, error)
	// 按手机号查询用户基础信息。
	QueryUserBasicInfo(context.Context, *QueryUserBasicInfoRequest) (*QueryUserBasicInfoResponse, error)
	mustEmbedUnimplementedUserAndDeviceQueryServiceServer()
}

// UnimplementedUserAndDeviceQueryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUserAndDeviceQueryServiceServer struct{}

func (UnimplementedUserAndDeviceQueryServiceServer) QueryDeviceBindInfo(context.Context, *QueryDeviceBindInfoRequest) (*QueryDeviceBindInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method QueryDeviceBindInfo not implemented")
}
func (UnimplementedUserAndDeviceQueryServiceServer) QueryUserBasicInfo(context.Context, *QueryUserBasicInfoRequest) (*QueryUserBasicInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method QueryUserBasicInfo not implemented")
}
func (UnimplementedUserAndDeviceQueryServiceServer) mustEmbedUnimplementedUserAndDeviceQueryServiceServer() {
}
func (UnimplementedUserAndDeviceQueryServiceServer) testEmbeddedByValue() {}

// UnsafeUserAndDeviceQueryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserAndDeviceQueryServiceServer will
// result in compilation errors.
type UnsafeUserAndDeviceQueryServiceServer interface {
	mustEmbedUnimplementedUserAndDeviceQueryServiceServer()
}

func RegisterUserAndDeviceQueryServiceServer(s grpc.ServiceRegistrar, srv UserAndDeviceQueryServiceServer) {
	// If the following call panics, it indicates UnimplementedUserAndDeviceQueryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UserAndDeviceQueryService_ServiceDesc, srv)
}

func _UserAndDeviceQueryService_QueryDeviceBindInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryDeviceBindInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserAndDeviceQueryServiceServer).QueryDeviceBindInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserAndDeviceQueryService_QueryDeviceBindInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserAndDeviceQueryServiceServer).QueryDeviceBindInfo(ctx, req.(*QueryDeviceBindInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserAndDeviceQueryService_QueryUserBasicInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryUserBasicInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserAndDeviceQueryServiceServer).QueryUserBasicInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserAndDeviceQueryService_QueryUserBasicInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserAndDeviceQueryServiceServer).QueryUserBasicInfo(ctx, req.(*QueryUserBasicInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UserAndDeviceQueryService_ServiceDesc is the grpc.ServiceDesc for UserAndDeviceQueryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserAndDeviceQueryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "basicquery.UserAndDeviceQueryService",
	HandlerType: (*UserAndDeviceQueryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "QueryDeviceBindInfo",
			Handler:    _UserAndDeviceQueryService_QueryDeviceBindInfo_Handler,
		},
		{
			MethodName: "QueryUserBasicInfo",
			Handler:    _UserAndDeviceQueryService_QueryUserBasicInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user_and_device_query.proto",
}
