// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.29.3
// source: cmd_service.proto

package cmdsvr

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CloudPlatformService_SendCommand_FullMethodName = "/cmdsvr.CloudPlatformService/SendCommand"
)

// CloudPlatformServiceClient is the client API for CloudPlatformService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CloudPlatformServiceClient interface {
	// app-server 向 cloud-platform 下发设备指令
	SendCommand(ctx context.Context, in *SendCommandRequest, opts ...grpc.CallOption) (*SendCommandResponse, error)
}

type cloudPlatformServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCloudPlatformServiceClient(cc grpc.ClientConnInterface) CloudPlatformServiceClient {
	return &cloudPlatformServiceClient{cc}
}

func (c *cloudPlatformServiceClient) SendCommand(ctx context.Context, in *SendCommandRequest, opts ...grpc.CallOption) (*SendCommandResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendCommandResponse)
	err := c.cc.Invoke(ctx, CloudPlatformService_SendCommand_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CloudPlatformServiceServer is the server API for CloudPlatformService service.
// All implementations must embed UnimplementedCloudPlatformServiceServer
// for forward compatibility.
type CloudPlatformServiceServer interface {
	// app-server 向 cloud-platform 下发设备指令
	SendCommand(context.Context, *SendCommandRequest) (*SendCommandResponse, error)
	mustEmbedUnimplementedCloudPlatformServiceServer()
}

// UnimplementedCloudPlatformServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCloudPlatformServiceServer struct{}

func (UnimplementedCloudPlatformServiceServer) SendCommand(context.Context, *SendCommandRequest) (*SendCommandResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendCommand not implemented")
}
func (UnimplementedCloudPlatformServiceServer) mustEmbedUnimplementedCloudPlatformServiceServer() {}
func (UnimplementedCloudPlatformServiceServer) testEmbeddedByValue()                              {}

// UnsafeCloudPlatformServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CloudPlatformServiceServer will
// result in compilation errors.
type UnsafeCloudPlatformServiceServer interface {
	mustEmbedUnimplementedCloudPlatformServiceServer()
}

func RegisterCloudPlatformServiceServer(s grpc.ServiceRegistrar, srv CloudPlatformServiceServer) {
	// If the following call panics, it indicates UnimplementedCloudPlatformServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CloudPlatformService_ServiceDesc, srv)
}

func _CloudPlatformService_SendCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendCommandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudPlatformServiceServer).SendCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CloudPlatformService_SendCommand_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudPlatformServiceServer).SendCommand(ctx, req.(*SendCommandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CloudPlatformService_ServiceDesc is the grpc.ServiceDesc for CloudPlatformService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CloudPlatformService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cmdsvr.CloudPlatformService",
	HandlerType: (*CloudPlatformServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendCommand",
			Handler:    _CloudPlatformService_SendCommand_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cmd_service.proto",
}
