// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: cmd_service.proto

package cmdsvr

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SendCommandRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 指令类型
	CmdType string `protobuf:"bytes,1,opt,name=cmdType,proto3" json:"cmdType,omitempty"`
	// 设备 ID
	DeviceId string `protobuf:"bytes,2,opt,name=deviceId,proto3" json:"deviceId,omitempty"`
	// 用户手机号
	Phone string `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	// 设备 SN
	DeviceSn string `protobuf:"bytes,4,opt,name=deviceSn,proto3" json:"deviceSn,omitempty"`
	// 指令载荷，调用方按业务约定传递 JSON 或普通字符串
	Payload       string `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendCommandRequest) Reset() {
	*x = SendCommandRequest{}
	mi := &file_cmd_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendCommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendCommandRequest) ProtoMessage() {}

func (x *SendCommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendCommandRequest.ProtoReflect.Descriptor instead.
func (*SendCommandRequest) Descriptor() ([]byte, []int) {
	return file_cmd_service_proto_rawDescGZIP(), []int{0}
}

func (x *SendCommandRequest) GetCmdType() string {
	if x != nil {
		return x.CmdType
	}
	return ""
}

func (x *SendCommandRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *SendCommandRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *SendCommandRequest) GetDeviceSn() string {
	if x != nil {
		return x.DeviceSn
	}
	return ""
}

func (x *SendCommandRequest) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

type SendCommandResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 状态码，0 表示成功，其他表示失败
	Code int32 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	// 结果说明
	Msg           string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendCommandResponse) Reset() {
	*x = SendCommandResponse{}
	mi := &file_cmd_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendCommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendCommandResponse) ProtoMessage() {}

func (x *SendCommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendCommandResponse.ProtoReflect.Descriptor instead.
func (*SendCommandResponse) Descriptor() ([]byte, []int) {
	return file_cmd_service_proto_rawDescGZIP(), []int{1}
}

func (x *SendCommandResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *SendCommandResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_cmd_service_proto protoreflect.FileDescriptor

const file_cmd_service_proto_rawDesc = "" +
	"\n" +
	"\x11cmd_service.proto\x12\x06cmdsvr\"\x96\x01\n" +
	"\x12SendCommandRequest\x12\x18\n" +
	"\acmdType\x18\x01 \x01(\tR\acmdType\x12\x1a\n" +
	"\bdeviceId\x18\x02 \x01(\tR\bdeviceId\x12\x14\n" +
	"\x05phone\x18\x03 \x01(\tR\x05phone\x12\x1a\n" +
	"\bdeviceSn\x18\x04 \x01(\tR\bdeviceSn\x12\x18\n" +
	"\apayload\x18\x05 \x01(\tR\apayload\";\n" +
	"\x13SendCommandResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg2^\n" +
	"\x14CloudPlatformService\x12F\n" +
	"\vSendCommand\x12\x1a.cmdsvr.SendCommandRequest\x1a\x1b.cmdsvr.SendCommandResponseB\x1cZ\x1aservice/cmd_service;cmdsvrb\x06proto3"

var (
	file_cmd_service_proto_rawDescOnce sync.Once
	file_cmd_service_proto_rawDescData []byte
)

func file_cmd_service_proto_rawDescGZIP() []byte {
	file_cmd_service_proto_rawDescOnce.Do(func() {
		file_cmd_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cmd_service_proto_rawDesc), len(file_cmd_service_proto_rawDesc)))
	})
	return file_cmd_service_proto_rawDescData
}

var file_cmd_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_cmd_service_proto_goTypes = []any{
	(*SendCommandRequest)(nil),  // 0: cmdsvr.SendCommandRequest
	(*SendCommandResponse)(nil), // 1: cmdsvr.SendCommandResponse
}
var file_cmd_service_proto_depIdxs = []int32{
	0, // 0: cmdsvr.CloudPlatformService.SendCommand:input_type -> cmdsvr.SendCommandRequest
	1, // 1: cmdsvr.CloudPlatformService.SendCommand:output_type -> cmdsvr.SendCommandResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_cmd_service_proto_init() }
func file_cmd_service_proto_init() {
	if File_cmd_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cmd_service_proto_rawDesc), len(file_cmd_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cmd_service_proto_goTypes,
		DependencyIndexes: file_cmd_service_proto_depIdxs,
		MessageInfos:      file_cmd_service_proto_msgTypes,
	}.Build()
	File_cmd_service_proto = out.File
	file_cmd_service_proto_goTypes = nil
	file_cmd_service_proto_depIdxs = nil
}
