// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.29.3
// source: device.proto

package devicesvr

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DeviceService_GetDevicesBySnList_FullMethodName       = "/devicesvr.DeviceService/GetDevicesBySnList"
	DeviceService_SearchDevicesByCondition_FullMethodName = "/devicesvr.DeviceService/SearchDevicesByCondition"
	DeviceService_UpdateDeviceAlias_FullMethodName        = "/devicesvr.DeviceService/UpdateDeviceAlias"
)

// DeviceServiceClient is the client API for DeviceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DeviceServiceClient interface {
	// 根据 SN 列表批量查询设备信息
	GetDevicesBySnList(ctx context.Context, in *GetDevicesBySnListRequest, opts ...grpc.CallOption) (*GetDevicesInfoListResponse, error)
	// 根据 SN、名称、机器人类型查询设备信息
	SearchDevicesByCondition(ctx context.Context, in *SearchDevicesRequest, opts ...grpc.CallOption) (*GetDevicesInfoListResponse, error)
	// 根据 SN、deviceId 修改设备别名
	UpdateDeviceAlias(ctx context.Context, in *UpdateDeviceAliasRequest, opts ...grpc.CallOption) (*UpdateDeviceAliasResponse, error)
}

type deviceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDeviceServiceClient(cc grpc.ClientConnInterface) DeviceServiceClient {
	return &deviceServiceClient{cc}
}

func (c *deviceServiceClient) GetDevicesBySnList(ctx context.Context, in *GetDevicesBySnListRequest, opts ...grpc.CallOption) (*GetDevicesInfoListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDevicesInfoListResponse)
	err := c.cc.Invoke(ctx, DeviceService_GetDevicesBySnList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceServiceClient) SearchDevicesByCondition(ctx context.Context, in *SearchDevicesRequest, opts ...grpc.CallOption) (*GetDevicesInfoListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDevicesInfoListResponse)
	err := c.cc.Invoke(ctx, DeviceService_SearchDevicesByCondition_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceServiceClient) UpdateDeviceAlias(ctx context.Context, in *UpdateDeviceAliasRequest, opts ...grpc.CallOption) (*UpdateDeviceAliasResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateDeviceAliasResponse)
	err := c.cc.Invoke(ctx, DeviceService_UpdateDeviceAlias_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DeviceServiceServer is the server API for DeviceService service.
// All implementations must embed UnimplementedDeviceServiceServer
// for forward compatibility.
type DeviceServiceServer interface {
	// 根据 SN 列表批量查询设备信息
	GetDevicesBySnList(context.Context, *GetDevicesBySnListRequest) (*GetDevicesInfoListResponse, error)
	// 根据 SN、名称、机器人类型查询设备信息
	SearchDevicesByCondition(context.Context, *SearchDevicesRequest) (*GetDevicesInfoListResponse, error)
	// 根据 SN、deviceId 修改设备别名
	UpdateDeviceAlias(context.Context, *UpdateDeviceAliasRequest) (*UpdateDeviceAliasResponse, error)
	mustEmbedUnimplementedDeviceServiceServer()
}

// UnimplementedDeviceServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDeviceServiceServer struct{}

func (UnimplementedDeviceServiceServer) GetDevicesBySnList(context.Context, *GetDevicesBySnListRequest) (*GetDevicesInfoListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDevicesBySnList not implemented")
}
func (UnimplementedDeviceServiceServer) SearchDevicesByCondition(context.Context, *SearchDevicesRequest) (*GetDevicesInfoListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchDevicesByCondition not implemented")
}
func (UnimplementedDeviceServiceServer) UpdateDeviceAlias(context.Context, *UpdateDeviceAliasRequest) (*UpdateDeviceAliasResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateDeviceAlias not implemented")
}
func (UnimplementedDeviceServiceServer) mustEmbedUnimplementedDeviceServiceServer() {}
func (UnimplementedDeviceServiceServer) testEmbeddedByValue()                       {}

// UnsafeDeviceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DeviceServiceServer will
// result in compilation errors.
type UnsafeDeviceServiceServer interface {
	mustEmbedUnimplementedDeviceServiceServer()
}

func RegisterDeviceServiceServer(s grpc.ServiceRegistrar, srv DeviceServiceServer) {
	// If the following call panics, it indicates UnimplementedDeviceServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DeviceService_ServiceDesc, srv)
}

func _DeviceService_GetDevicesBySnList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDevicesBySnListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceServiceServer).GetDevicesBySnList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeviceService_GetDevicesBySnList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceServiceServer).GetDevicesBySnList(ctx, req.(*GetDevicesBySnListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeviceService_SearchDevicesByCondition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchDevicesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceServiceServer).SearchDevicesByCondition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeviceService_SearchDevicesByCondition_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceServiceServer).SearchDevicesByCondition(ctx, req.(*SearchDevicesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeviceService_UpdateDeviceAlias_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDeviceAliasRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceServiceServer).UpdateDeviceAlias(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeviceService_UpdateDeviceAlias_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceServiceServer).UpdateDeviceAlias(ctx, req.(*UpdateDeviceAliasRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DeviceService_ServiceDesc is the grpc.ServiceDesc for DeviceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DeviceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "devicesvr.DeviceService",
	HandlerType: (*DeviceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDevicesBySnList",
			Handler:    _DeviceService_GetDevicesBySnList_Handler,
		},
		{
			MethodName: "SearchDevicesByCondition",
			Handler:    _DeviceService_SearchDevicesByCondition_Handler,
		},
		{
			MethodName: "UpdateDeviceAlias",
			Handler:    _DeviceService_UpdateDeviceAlias_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "device.proto",
}
