// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: device.proto

package devicesvr

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// QueryType 设备查询类型
type QueryType int32

const (
	QueryType_QUERY_TYPE_UNSPECIFIED    QueryType = 0 // 未指定（按条件组合查询）
	QueryType_QUERY_TYPE_BY_SN          QueryType = 1 // 按设备序列号查询
	QueryType_QUERY_TYPE_BY_NAME        QueryType = 2 // 按设备名称查询
	QueryType_QUERY_TYPE_BY_DEVICE_TYPE QueryType = 3 // 按设备类型查询
	QueryType_QUERY_TYPE_BY_DEVICE_ID   QueryType = 4 // 按设备 ID 查询
	QueryType_QUERY_TYPE_BY_PID         QueryType = 5 // 按产品 ID 查询
)

// Enum value maps for QueryType.
var (
	QueryType_name = map[int32]string{
		0: "QUERY_TYPE_UNSPECIFIED",
		1: "QUERY_TYPE_BY_SN",
		2: "QUERY_TYPE_BY_NAME",
		3: "QUERY_TYPE_BY_DEVICE_TYPE",
		4: "QUERY_TYPE_BY_DEVICE_ID",
		5: "QUERY_TYPE_BY_PID",
	}
	QueryType_value = map[string]int32{
		"QUERY_TYPE_UNSPECIFIED":    0,
		"QUERY_TYPE_BY_SN":          1,
		"QUERY_TYPE_BY_NAME":        2,
		"QUERY_TYPE_BY_DEVICE_TYPE": 3,
		"QUERY_TYPE_BY_DEVICE_ID":   4,
		"QUERY_TYPE_BY_PID":         5,
	}
)

func (x QueryType) Enum() *QueryType {
	p := new(QueryType)
	*p = x
	return p
}

func (x QueryType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (QueryType) Descriptor() protoreflect.EnumDescriptor {
	return file_device_proto_enumTypes[0].Descriptor()
}

func (QueryType) Type() protoreflect.EnumType {
	return &file_device_proto_enumTypes[0]
}

func (x QueryType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use QueryType.Descriptor instead.
func (QueryType) EnumDescriptor() ([]byte, []int) {
	return file_device_proto_rawDescGZIP(), []int{0}
}

// GetDevicesBySnListRequest 根据 SN 列表查询设备信息
type GetDevicesBySnListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SnList        []string               `protobuf:"bytes,1,rep,name=snList,proto3" json:"snList,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDevicesBySnListRequest) Reset() {
	*x = GetDevicesBySnListRequest{}
	mi := &file_device_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDevicesBySnListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDevicesBySnListRequest) ProtoMessage() {}

func (x *GetDevicesBySnListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_device_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDevicesBySnListRequest.ProtoReflect.Descriptor instead.
func (*GetDevicesBySnListRequest) Descriptor() ([]byte, []int) {
	return file_device_proto_rawDescGZIP(), []int{0}
}

func (x *GetDevicesBySnListRequest) GetSnList() []string {
	if x != nil {
		return x.SnList
	}
	return nil
}

// DeviceInfo 设备信息（不包含敏感字段 scramble_code）
type DeviceInfo struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Id                     string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SnNumber               string                 `protobuf:"bytes,2,opt,name=snNumber,proto3" json:"snNumber,omitempty"`                              // 设备序列号
	ImeiNumber             string                 `protobuf:"bytes,3,opt,name=imeiNumber,proto3" json:"imeiNumber,omitempty"`                          // 设备 IMEI 号
	Owner                  string                 `protobuf:"bytes,4,opt,name=owner,proto3" json:"owner,omitempty"`                                    // 创建者/所有者
	OrgId                  int64                  `protobuf:"varint,5,opt,name=orgId,proto3" json:"orgId,omitempty"`                                   // 机构 ID
	CreateTime             *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=createTime,proto3" json:"createTime,omitempty"`                          // 创建时间
	UpdateTime             *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updateTime,proto3" json:"updateTime,omitempty"`                          // 更新时间
	Name                   string                 `protobuf:"bytes,8,opt,name=name,proto3" json:"name,omitempty"`                                      // 设备名称
	Token                  string                 `protobuf:"bytes,9,opt,name=token,proto3" json:"token,omitempty"`                                    // 设备 token
	Alias                  string                 `protobuf:"bytes,10,opt,name=alias,proto3" json:"alias,omitempty"`                                   // 设备别名
	Pid                    string                 `protobuf:"bytes,11,opt,name=pid,proto3" json:"pid,omitempty"`                                       // 产品 ID
	Gid                    string                 `protobuf:"bytes,12,opt,name=gid,proto3" json:"gid,omitempty"`                                       // 分组 ID
	Description            string                 `protobuf:"bytes,13,opt,name=description,proto3" json:"description,omitempty"`                       // 产品说明
	Status                 string                 `protobuf:"bytes,14,opt,name=status,proto3" json:"status,omitempty"`                                 // 状态
	FactoryInstallVersion  string                 `protobuf:"bytes,15,opt,name=factoryInstallVersion,proto3" json:"factoryInstallVersion,omitempty"`   // 出厂安装版本
	FactoryDownloadVersion string                 `protobuf:"bytes,16,opt,name=factoryDownloadVersion,proto3" json:"factoryDownloadVersion,omitempty"` // 出厂下载版本
	OtaVersion             string                 `protobuf:"bytes,17,opt,name=otaVersion,proto3" json:"otaVersion,omitempty"`                         // 固件版本（已废弃，向后兼容）
	RosDomainId            int64                  `protobuf:"varint,18,opt,name=rosDomainId,proto3" json:"rosDomainId,omitempty"`                      // ROS 域 ID
	ParentId               string                 `protobuf:"bytes,19,opt,name=parentId,proto3" json:"parentId,omitempty"`                             // 父设备 ID（子设备时父设备为网关）
	DeviceType             string                 `protobuf:"bytes,20,opt,name=deviceType,proto3" json:"deviceType,omitempty"`                         // 设备类型
	LinkStatus             string                 `protobuf:"bytes,21,opt,name=linkStatus,proto3" json:"linkStatus,omitempty"`                         // 连接状态
	LastTime               *timestamppb.Timestamp `protobuf:"bytes,22,opt,name=lastTime,proto3" json:"lastTime,omitempty"`                             // 最后一次在线时间
	LifecycleStatus        string                 `protobuf:"bytes,23,opt,name=lifecycleStatus,proto3" json:"lifecycleStatus,omitempty"`               // 生命周期状态
	DeviceBelongingType    string                 `protobuf:"bytes,24,opt,name=deviceBelongingType,proto3" json:"deviceBelongingType,omitempty"`       // 设备归属类型
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *DeviceInfo) Reset() {
	*x = DeviceInfo{}
	mi := &file_device_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceInfo) ProtoMessage() {}

func (x *DeviceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_device_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceInfo.ProtoReflect.Descriptor instead.
func (*DeviceInfo) Descriptor() ([]byte, []int) {
	return file_device_proto_rawDescGZIP(), []int{1}
}

func (x *DeviceInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeviceInfo) GetSnNumber() string {
	if x != nil {
		return x.SnNumber
	}
	return ""
}

func (x *DeviceInfo) GetImeiNumber() string {
	if x != nil {
		return x.ImeiNumber
	}
	return ""
}

func (x *DeviceInfo) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *DeviceInfo) GetOrgId() int64 {
	if x != nil {
		return x.OrgId
	}
	return 0
}

func (x *DeviceInfo) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *DeviceInfo) GetUpdateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateTime
	}
	return nil
}

func (x *DeviceInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DeviceInfo) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *DeviceInfo) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

func (x *DeviceInfo) GetPid() string {
	if x != nil {
		return x.Pid
	}
	return ""
}

func (x *DeviceInfo) GetGid() string {
	if x != nil {
		return x.Gid
	}
	return ""
}

func (x *DeviceInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *DeviceInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *DeviceInfo) GetFactoryInstallVersion() string {
	if x != nil {
		return x.FactoryInstallVersion
	}
	return ""
}

func (x *DeviceInfo) GetFactoryDownloadVersion() string {
	if x != nil {
		return x.FactoryDownloadVersion
	}
	return ""
}

func (x *DeviceInfo) GetOtaVersion() string {
	if x != nil {
		return x.OtaVersion
	}
	return ""
}

func (x *DeviceInfo) GetRosDomainId() int64 {
	if x != nil {
		return x.RosDomainId
	}
	return 0
}

func (x *DeviceInfo) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

func (x *DeviceInfo) GetDeviceType() string {
	if x != nil {
		return x.DeviceType
	}
	return ""
}

func (x *DeviceInfo) GetLinkStatus() string {
	if x != nil {
		return x.LinkStatus
	}
	return ""
}

func (x *DeviceInfo) GetLastTime() *timestamppb.Timestamp {
	if x != nil {
		return x.LastTime
	}
	return nil
}

func (x *DeviceInfo) GetLifecycleStatus() string {
	if x != nil {
		return x.LifecycleStatus
	}
	return ""
}

func (x *DeviceInfo) GetDeviceBelongingType() string {
	if x != nil {
		return x.DeviceBelongingType
	}
	return ""
}

// GetDevicesBySnListResponse 设备信息列表
type GetDevicesInfoListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Devices       []*DeviceInfo          `protobuf:"bytes,1,rep,name=devices,proto3" json:"devices,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`       // 总设备数
	Page          int64                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`         // 页码
	PageSize      int64                  `protobuf:"varint,4,opt,name=pageSize,proto3" json:"pageSize,omitempty"` // 每页设备数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDevicesInfoListResponse) Reset() {
	*x = GetDevicesInfoListResponse{}
	mi := &file_device_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDevicesInfoListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDevicesInfoListResponse) ProtoMessage() {}

func (x *GetDevicesInfoListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_device_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDevicesInfoListResponse.ProtoReflect.Descriptor instead.
func (*GetDevicesInfoListResponse) Descriptor() ([]byte, []int) {
	return file_device_proto_rawDescGZIP(), []int{2}
}

func (x *GetDevicesInfoListResponse) GetDevices() []*DeviceInfo {
	if x != nil {
		return x.Devices
	}
	return nil
}

func (x *GetDevicesInfoListResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GetDevicesInfoListResponse) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetDevicesInfoListResponse) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// SearchDevicesRequest 根据 SN、名称、机器人类型查询设备信息（条件可选，支持组合查询）
type SearchDevicesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SnNumber      string                 `protobuf:"bytes,1,opt,name=snNumber,proto3" json:"snNumber,omitempty"`                             // 设备序列号（精确匹配，空则忽略）
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                                     // 设备名称（模糊匹配，空则忽略）
	DeviceType    string                 `protobuf:"bytes,3,opt,name=deviceType,proto3" json:"deviceType,omitempty"`                         // 机器人类型/设备类型（精确匹配，空则忽略）
	DeviceId      string                 `protobuf:"bytes,4,opt,name=deviceId,proto3" json:"deviceId,omitempty"`                             //设备id
	Pid           string                 `protobuf:"bytes,5,opt,name=pid,proto3" json:"pid,omitempty"`                                       //产品id
	QueryType     QueryType              `protobuf:"varint,6,opt,name=queryType,proto3,enum=devicesvr.QueryType" json:"queryType,omitempty"` // 查询类型
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchDevicesRequest) Reset() {
	*x = SearchDevicesRequest{}
	mi := &file_device_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchDevicesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchDevicesRequest) ProtoMessage() {}

func (x *SearchDevicesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_device_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchDevicesRequest.ProtoReflect.Descriptor instead.
func (*SearchDevicesRequest) Descriptor() ([]byte, []int) {
	return file_device_proto_rawDescGZIP(), []int{3}
}

func (x *SearchDevicesRequest) GetSnNumber() string {
	if x != nil {
		return x.SnNumber
	}
	return ""
}

func (x *SearchDevicesRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SearchDevicesRequest) GetDeviceType() string {
	if x != nil {
		return x.DeviceType
	}
	return ""
}

func (x *SearchDevicesRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *SearchDevicesRequest) GetPid() string {
	if x != nil {
		return x.Pid
	}
	return ""
}

func (x *SearchDevicesRequest) GetQueryType() QueryType {
	if x != nil {
		return x.QueryType
	}
	return QueryType_QUERY_TYPE_UNSPECIFIED
}

var File_device_proto protoreflect.FileDescriptor

const file_device_proto_rawDesc = "" +
	"\n" +
	"\fdevice.proto\x12\tdevicesvr\x1a\x1fgoogle/protobuf/timestamp.proto\"3\n" +
	"\x19GetDevicesBySnListRequest\x12\x16\n" +
	"\x06snList\x18\x01 \x03(\tR\x06snList\"\xba\x06\n" +
	"\n" +
	"DeviceInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bsnNumber\x18\x02 \x01(\tR\bsnNumber\x12\x1e\n" +
	"\n" +
	"imeiNumber\x18\x03 \x01(\tR\n" +
	"imeiNumber\x12\x14\n" +
	"\x05owner\x18\x04 \x01(\tR\x05owner\x12\x14\n" +
	"\x05orgId\x18\x05 \x01(\x03R\x05orgId\x12:\n" +
	"\n" +
	"createTime\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"createTime\x12:\n" +
	"\n" +
	"updateTime\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"updateTime\x12\x12\n" +
	"\x04name\x18\b \x01(\tR\x04name\x12\x14\n" +
	"\x05token\x18\t \x01(\tR\x05token\x12\x14\n" +
	"\x05alias\x18\n" +
	" \x01(\tR\x05alias\x12\x10\n" +
	"\x03pid\x18\v \x01(\tR\x03pid\x12\x10\n" +
	"\x03gid\x18\f \x01(\tR\x03gid\x12 \n" +
	"\vdescription\x18\r \x01(\tR\vdescription\x12\x16\n" +
	"\x06status\x18\x0e \x01(\tR\x06status\x124\n" +
	"\x15factoryInstallVersion\x18\x0f \x01(\tR\x15factoryInstallVersion\x126\n" +
	"\x16factoryDownloadVersion\x18\x10 \x01(\tR\x16factoryDownloadVersion\x12\x1e\n" +
	"\n" +
	"otaVersion\x18\x11 \x01(\tR\n" +
	"otaVersion\x12 \n" +
	"\vrosDomainId\x18\x12 \x01(\x03R\vrosDomainId\x12\x1a\n" +
	"\bparentId\x18\x13 \x01(\tR\bparentId\x12\x1e\n" +
	"\n" +
	"deviceType\x18\x14 \x01(\tR\n" +
	"deviceType\x12\x1e\n" +
	"\n" +
	"linkStatus\x18\x15 \x01(\tR\n" +
	"linkStatus\x126\n" +
	"\blastTime\x18\x16 \x01(\v2\x1a.google.protobuf.TimestampR\blastTime\x12(\n" +
	"\x0flifecycleStatus\x18\x17 \x01(\tR\x0flifecycleStatus\x120\n" +
	"\x13deviceBelongingType\x18\x18 \x01(\tR\x13deviceBelongingType\"\x93\x01\n" +
	"\x1aGetDevicesInfoListResponse\x12/\n" +
	"\adevices\x18\x01 \x03(\v2\x15.devicesvr.DeviceInfoR\adevices\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x03R\x04page\x12\x1a\n" +
	"\bpageSize\x18\x04 \x01(\x03R\bpageSize\"\xc8\x01\n" +
	"\x14SearchDevicesRequest\x12\x1a\n" +
	"\bsnNumber\x18\x01 \x01(\tR\bsnNumber\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1e\n" +
	"\n" +
	"deviceType\x18\x03 \x01(\tR\n" +
	"deviceType\x12\x1a\n" +
	"\bdeviceId\x18\x04 \x01(\tR\bdeviceId\x12\x10\n" +
	"\x03pid\x18\x05 \x01(\tR\x03pid\x122\n" +
	"\tqueryType\x18\x06 \x01(\x0e2\x14.devicesvr.QueryTypeR\tqueryType*\xa8\x01\n" +
	"\tQueryType\x12\x1a\n" +
	"\x16QUERY_TYPE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10QUERY_TYPE_BY_SN\x10\x01\x12\x16\n" +
	"\x12QUERY_TYPE_BY_NAME\x10\x02\x12\x1d\n" +
	"\x19QUERY_TYPE_BY_DEVICE_TYPE\x10\x03\x12\x1b\n" +
	"\x17QUERY_TYPE_BY_DEVICE_ID\x10\x04\x12\x15\n" +
	"\x11QUERY_TYPE_BY_PID\x10\x052\xd6\x01\n" +
	"\rDeviceService\x12a\n" +
	"\x12GetDevicesBySnList\x12$.devicesvr.GetDevicesBySnListRequest\x1a%.devicesvr.GetDevicesInfoListResponse\x12b\n" +
	"\x18SearchDevicesByCondition\x12\x1f.devicesvr.SearchDevicesRequest\x1a%.devicesvr.GetDevicesInfoListResponseB\x1aZ\x18service/device;devicesvrb\x06proto3"

var (
	file_device_proto_rawDescOnce sync.Once
	file_device_proto_rawDescData []byte
)

func file_device_proto_rawDescGZIP() []byte {
	file_device_proto_rawDescOnce.Do(func() {
		file_device_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_device_proto_rawDesc), len(file_device_proto_rawDesc)))
	})
	return file_device_proto_rawDescData
}

var file_device_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_device_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_device_proto_goTypes = []any{
	(QueryType)(0),                     // 0: devicesvr.QueryType
	(*GetDevicesBySnListRequest)(nil),  // 1: devicesvr.GetDevicesBySnListRequest
	(*DeviceInfo)(nil),                 // 2: devicesvr.DeviceInfo
	(*GetDevicesInfoListResponse)(nil), // 3: devicesvr.GetDevicesInfoListResponse
	(*SearchDevicesRequest)(nil),       // 4: devicesvr.SearchDevicesRequest
	(*timestamppb.Timestamp)(nil),      // 5: google.protobuf.Timestamp
}
var file_device_proto_depIdxs = []int32{
	5, // 0: devicesvr.DeviceInfo.createTime:type_name -> google.protobuf.Timestamp
	5, // 1: devicesvr.DeviceInfo.updateTime:type_name -> google.protobuf.Timestamp
	5, // 2: devicesvr.DeviceInfo.lastTime:type_name -> google.protobuf.Timestamp
	2, // 3: devicesvr.GetDevicesInfoListResponse.devices:type_name -> devicesvr.DeviceInfo
	0, // 4: devicesvr.SearchDevicesRequest.queryType:type_name -> devicesvr.QueryType
	1, // 5: devicesvr.DeviceService.GetDevicesBySnList:input_type -> devicesvr.GetDevicesBySnListRequest
	4, // 6: devicesvr.DeviceService.SearchDevicesByCondition:input_type -> devicesvr.SearchDevicesRequest
	3, // 7: devicesvr.DeviceService.GetDevicesBySnList:output_type -> devicesvr.GetDevicesInfoListResponse
	3, // 8: devicesvr.DeviceService.SearchDevicesByCondition:output_type -> devicesvr.GetDevicesInfoListResponse
	7, // [7:9] is the sub-list for method output_type
	5, // [5:7] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_device_proto_init() }
func file_device_proto_init() {
	if File_device_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_device_proto_rawDesc), len(file_device_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_device_proto_goTypes,
		DependencyIndexes: file_device_proto_depIdxs,
		EnumInfos:         file_device_proto_enumTypes,
		MessageInfos:      file_device_proto_msgTypes,
	}.Build()
	File_device_proto = out.File
	file_device_proto_goTypes = nil
	file_device_proto_depIdxs = nil
}
