// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: user.proto

package usersvr

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OperType int32

const (
	OperType_OPER_TYPE_UNSPECIFIED OperType = 0
	OperType_OPER_TYPE_INSERT      OperType = 1
	OperType_OPER_TYPE_UPDATE      OperType = 2
)

// Enum value maps for OperType.
var (
	OperType_name = map[int32]string{
		0: "OPER_TYPE_UNSPECIFIED",
		1: "OPER_TYPE_INSERT",
		2: "OPER_TYPE_UPDATE",
	}
	OperType_value = map[string]int32{
		"OPER_TYPE_UNSPECIFIED": 0,
		"OPER_TYPE_INSERT":      1,
		"OPER_TYPE_UPDATE":      2,
	}
)

func (x OperType) Enum() *OperType {
	p := new(OperType)
	*p = x
	return p
}

func (x OperType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OperType) Descriptor() protoreflect.EnumDescriptor {
	return file_user_proto_enumTypes[0].Descriptor()
}

func (OperType) Type() protoreflect.EnumType {
	return &file_user_proto_enumTypes[0]
}

func (x OperType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OperType.Descriptor instead.
func (OperType) EnumDescriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{0}
}

type DataType int32

const (
	DataType_DATA_TYPE_UNSPECIFIED       DataType = 0
	DataType_DATA_TYPE_FOLLOW_PERMISSION DataType = 1
	DataType_DATA_TYPE_TRIGGER_INFO      DataType = 2
)

// Enum value maps for DataType.
var (
	DataType_name = map[int32]string{
		0: "DATA_TYPE_UNSPECIFIED",
		1: "DATA_TYPE_FOLLOW_PERMISSION",
		2: "DATA_TYPE_TRIGGER_INFO",
	}
	DataType_value = map[string]int32{
		"DATA_TYPE_UNSPECIFIED":       0,
		"DATA_TYPE_FOLLOW_PERMISSION": 1,
		"DATA_TYPE_TRIGGER_INFO":      2,
	}
)

func (x DataType) Enum() *DataType {
	p := new(DataType)
	*p = x
	return p
}

func (x DataType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DataType) Descriptor() protoreflect.EnumDescriptor {
	return file_user_proto_enumTypes[1].Descriptor()
}

func (DataType) Type() protoreflect.EnumType {
	return &file_user_proto_enumTypes[1]
}

func (x DataType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DataType.Descriptor instead.
func (DataType) EnumDescriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{1}
}

type UpdateUserDataRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 操作类型
	OperType OperType `protobuf:"varint,1,opt,name=operType,proto3,enum=usersvr.OperType" json:"operType,omitempty"`
	// 数据类型
	DataType DataType `protobuf:"varint,2,opt,name=dataType,proto3,enum=usersvr.DataType" json:"dataType,omitempty"`
	// 数据内容，支持字符串、数字、布尔值、对象和数组等类型
	Data          *structpb.Struct `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserDataRequest) Reset() {
	*x = UpdateUserDataRequest{}
	mi := &file_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserDataRequest) ProtoMessage() {}

func (x *UpdateUserDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserDataRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserDataRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{0}
}

func (x *UpdateUserDataRequest) GetOperType() OperType {
	if x != nil {
		return x.OperType
	}
	return OperType_OPER_TYPE_UNSPECIFIED
}

func (x *UpdateUserDataRequest) GetDataType() DataType {
	if x != nil {
		return x.DataType
	}
	return DataType_DATA_TYPE_UNSPECIFIED
}

func (x *UpdateUserDataRequest) GetData() *structpb.Struct {
	if x != nil {
		return x.Data
	}
	return nil
}

type UpdateUserDataResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 状态码：0 表示成功，其他表示失败
	Code int32 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	// 结果说明
	Message       string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserDataResponse) Reset() {
	*x = UpdateUserDataResponse{}
	mi := &file_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserDataResponse) ProtoMessage() {}

func (x *UpdateUserDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserDataResponse.ProtoReflect.Descriptor instead.
func (*UpdateUserDataResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateUserDataResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *UpdateUserDataResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_user_proto protoreflect.FileDescriptor

const file_user_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"user.proto\x12\ausersvr\x1a\x1cgoogle/protobuf/struct.proto\"\xa2\x01\n" +
	"\x15UpdateUserDataRequest\x12-\n" +
	"\boperType\x18\x01 \x01(\x0e2\x11.usersvr.OperTypeR\boperType\x12-\n" +
	"\bdataType\x18\x02 \x01(\x0e2\x11.usersvr.DataTypeR\bdataType\x12+\n" +
	"\x04data\x18\x03 \x01(\v2\x17.google.protobuf.StructR\x04data\"F\n" +
	"\x16UpdateUserDataResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage*Q\n" +
	"\bOperType\x12\x19\n" +
	"\x15OPER_TYPE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10OPER_TYPE_INSERT\x10\x01\x12\x14\n" +
	"\x10OPER_TYPE_UPDATE\x10\x02*b\n" +
	"\bDataType\x12\x19\n" +
	"\x15DATA_TYPE_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bDATA_TYPE_FOLLOW_PERMISSION\x10\x01\x12\x1a\n" +
	"\x16DATA_TYPE_TRIGGER_INFO\x10\x022`\n" +
	"\vUserService\x12Q\n" +
	"\x0eUpdateUserData\x12\x1e.usersvr.UpdateUserDataRequest\x1a\x1f.usersvr.UpdateUserDataResponseB\x16Z\x14service/user;usersvrb\x06proto3"

var (
	file_user_proto_rawDescOnce sync.Once
	file_user_proto_rawDescData []byte
)

func file_user_proto_rawDescGZIP() []byte {
	file_user_proto_rawDescOnce.Do(func() {
		file_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)))
	})
	return file_user_proto_rawDescData
}

var file_user_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_user_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_user_proto_goTypes = []any{
	(OperType)(0),                  // 0: usersvr.OperType
	(DataType)(0),                  // 1: usersvr.DataType
	(*UpdateUserDataRequest)(nil),  // 2: usersvr.UpdateUserDataRequest
	(*UpdateUserDataResponse)(nil), // 3: usersvr.UpdateUserDataResponse
	(*structpb.Struct)(nil),        // 4: google.protobuf.Struct
}
var file_user_proto_depIdxs = []int32{
	0, // 0: usersvr.UpdateUserDataRequest.operType:type_name -> usersvr.OperType
	1, // 1: usersvr.UpdateUserDataRequest.dataType:type_name -> usersvr.DataType
	4, // 2: usersvr.UpdateUserDataRequest.data:type_name -> google.protobuf.Struct
	2, // 3: usersvr.UserService.UpdateUserData:input_type -> usersvr.UpdateUserDataRequest
	3, // 4: usersvr.UserService.UpdateUserData:output_type -> usersvr.UpdateUserDataResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_user_proto_init() }
func file_user_proto_init() {
	if File_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_proto_goTypes,
		DependencyIndexes: file_user_proto_depIdxs,
		EnumInfos:         file_user_proto_enumTypes,
		MessageInfos:      file_user_proto_msgTypes,
	}.Build()
	File_user_proto = out.File
	file_user_proto_goTypes = nil
	file_user_proto_depIdxs = nil
}
